// The Isolation code view (PLAN V1, with the V3 git view folded in) — a first-party
// Monaco editor over the doorman's execd-backed file API. Served at /v/<viewId>/ by
// isolation-server itself: no process in the sandbox, no code-server. Direct links
// carry the location in the QUERY (?file=<workspace-relative-path>&line=<n>) so the
// doorman's routing stays untouched, and a mounted view navigates in place on a
// `isolation:open` postMessage instead of reloading.
//
// The sidebar is a full file explorer: create/rename/duplicate/delete via a context
// menu, drag-and-drop move (plus OS-file drop = upload), download, clipboard-style
// copy/paste, keyboard navigation, and refresh-on-focus. Saves are stale-guarded:
// the server refuses a write when the file moved underneath the editor.
//
// Source control (VS Code-shaped): a collapsible section under the tree lists every
// NESTED repo's working state (the workspace root is the session branch — session
// sync's job, never shown here) with stage/unstage/discard/commit/push/pull/branches;
// tree rows are colored + badged by git status; the file menu grows a Git section; a
// change opens as a Monaco diff tab whose right side is the live, saveable buffer.
// The slim entry (generated by scripts/build-editor.mjs): the full editor + monarch
// syntax highlighting, WITHOUT the worker-backed css/html/json/typescript language
// services — projectless single-file services mark every cross-file import as an
// error and need workers we don't ship.
import * as monaco from "monaco-editor/editor/editor.slim.main.js";
import "./editor.css";

// Monaco's language smarts run in a worker; we bundle the base worker next to main.js.
// __WORKER_V__ is stamped by build-editor.mjs so a server upgrade busts the asset cache.
declare const __WORKER_V__: string;
(self as unknown as { MonacoEnvironment: unknown }).MonacoEnvironment = {
  getWorker: () => new Worker(new URL(`./editor.worker.js?v=${__WORKER_V__}`, location.href)),
};

const $ = <T extends HTMLElement>(id: string): T => document.getElementById(id) as T;
const treeEl = $("tree");
const tabsEl = $("tabs");
const emptyEl = $("empty-state");
const statusPath = $("status-path");
const statusLang = $("status-lang");
const statusMsg = $("status-msg");

const MAX_UPLOAD = 10 * 1024 * 1024; // mirrors the server cap

// --- api ------------------------------------------------------------------------

interface Entry {
  name: string;
  dir: boolean;
}

const errorOf = async (r: Response): Promise<string> => ((await r.json().catch(() => ({}))) as { error?: string }).error ?? `HTTP ${r.status}`;

async function apiList(path: string): Promise<Entry[]> {
  const r = await fetch(`api/list?path=${encodeURIComponent(path)}`);
  if (!r.ok) throw new Error(await errorOf(r));
  return ((await r.json()) as { entries: Entry[] }).entries;
}

async function apiRead(path: string): Promise<{ bytes: ArrayBuffer; mtime?: number }> {
  const r = await fetch(`api/file?path=${encodeURIComponent(path)}`);
  if (!r.ok) throw new Error(await errorOf(r));
  const mtime = Number(r.headers.get("X-Iso-Mtime")) || undefined;
  return { bytes: await r.arrayBuffer(), mtime };
}

// Save with the stale gate; expectMtime undefined = unconditional write.
async function apiSave(path: string, content: string | Blob, expectMtime?: number): Promise<{ mtime?: number }> {
  const r = await fetch(`api/file?path=${encodeURIComponent(path)}`, {
    method: "PUT",
    body: content,
    headers: expectMtime ? { "X-Iso-Expect-Mtime": String(expectMtime) } : {},
  });
  const body = (await r.json().catch(() => ({}))) as { error?: string; stale?: boolean; mtime?: number };
  if (!r.ok) {
    const e = new Error(body.error ?? `HTTP ${r.status}`) as Error & { stale?: boolean };
    e.stale = body.stale;
    throw e;
  }
  return { mtime: body.mtime };
}

// mtimes for a batch of workspace files; 0 = gone. The "did it change under me" probe.
async function apiStat(paths: string[]): Promise<Record<string, number>> {
  const r = await fetch(`api/stat?${paths.map((p) => `path=${encodeURIComponent(p)}`).join("&")}`);
  if (!r.ok) throw new Error(await errorOf(r));
  return ((await r.json()) as { mtimes: Record<string, number> }).mtimes;
}

async function apiOp(op: string, path: string, to?: string): Promise<void> {
  const r = await fetch("api/op", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ op, path, ...(to ? { to } : {}) }),
  });
  if (!r.ok) throw new Error(await errorOf(r));
}

// --- git api --------------------------------------------------------------------

interface StatusFile {
  path: string; // repo-relative
  index: string;
  work: string;
  renamedFrom?: string;
}

interface RepoStatus {
  dir: string; // workspace-relative
  branch: string;
  detached: boolean;
  upstream: boolean;
  ahead: number;
  behind: number;
  files: StatusFile[];
  ignored: string[];
  remote?: string;
  error?: string;
}

async function apiGitStatus(): Promise<RepoStatus[]> {
  const r = await fetch("api/git/status");
  if (!r.ok) throw new Error(await errorOf(r));
  return ((await r.json()) as { repos: RepoStatus[] }).repos;
}

async function apiGitShow(repo: string, rel: string, rev: "head" | "index"): Promise<{ content: string | null; binary?: boolean }> {
  const r = await fetch(`api/git/show?repo=${encodeURIComponent(repo)}&path=${encodeURIComponent(rel)}&rev=${rev}`);
  if (!r.ok) throw new Error(await errorOf(r));
  return (await r.json()) as { content: string | null; binary?: boolean };
}

async function apiGitBranches(repo: string): Promise<{ current: string; local: string[]; remote: string[] }> {
  const r = await fetch(`api/git/branches?repo=${encodeURIComponent(repo)}`);
  if (!r.ok) throw new Error(await errorOf(r));
  return (await r.json()) as { current: string; local: string[]; remote: string[] };
}

async function apiGitOp(repo: string, body: Record<string, unknown>): Promise<string> {
  const r = await fetch("api/git/op", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ repo, ...body }),
  });
  const out = (await r.json().catch(() => ({}))) as { error?: string; output?: string };
  if (!r.ok) throw new Error(out.error ?? `HTTP ${r.status}`);
  return out.output ?? "";
}

// --- status ---------------------------------------------------------------------

let msgTimer: number | undefined;
function flash(text: string, isError = false): void {
  statusMsg.textContent = text;
  statusMsg.classList.toggle("error", isError);
  if (msgTimer) clearTimeout(msgTimer);
  if (!isError) msgTimer = window.setTimeout(() => (statusMsg.textContent = ""), 2500);
}

const basename = (p: string): string => p.split("/").pop() ?? p;
const parentOf = (p: string): string => (p.includes("/") ? p.slice(0, p.lastIndexOf("/")) : "");

// --- editor ---------------------------------------------------------------------

monaco.editor.defineTheme("isolation-dark", {
  base: "vs-dark",
  inherit: true,
  rules: [],
  colors: {
    "editor.background": "#0b0d10",
    "editor.lineHighlightBackground": "#12161c",
    "editorLineNumber.foreground": "#3d4652",
    "editorLineNumber.activeForeground": "#9aa4b2",
    "editorGutter.background": "#0b0d10",
    "editorWidget.background": "#101318",
    "editorWidget.border": "#232a33",
    "focusBorder": "#232a33",
    "scrollbarSlider.background": "#232a3366",
    "scrollbarSlider.hoverBackground": "#232a33aa",
    "diffEditor.insertedLineBackground": "#3fb95018",
    "diffEditor.removedLineBackground": "#f8514918",
    "diffEditor.insertedTextBackground": "#3fb95033",
    "diffEditor.removedTextBackground": "#f8514933",
  },
});

const editorOpts: monaco.editor.IStandaloneEditorConstructionOptions = {
  theme: "isolation-dark",
  automaticLayout: true,
  fontSize: 13,
  minimap: { enabled: false },
  scrollBeyondLastLine: false,
  renderWhitespace: "none",
  smoothScrolling: true,
  padding: { top: 8 },
  stickyScroll: { enabled: false },
};

const editor = monaco.editor.create($("editor"), editorOpts);
// Diffs (VS Code's "Open Changes"): side by side, folding to inline when the pane is
// narrow. The original side is never editable; the modified side is the live buffer.
const diffHost = $("diff-editor");
const diffEditor = monaco.editor.createDiffEditor(diffHost, {
  ...editorOpts,
  renderSideBySide: true,
  useInlineViewWhenSpaceIsLimited: true,
  renderSideBySideInlineBreakpoint: 760,
  originalEditable: false,
  renderOverviewRuler: false,
  ignoreTrimWhitespace: false,
  diffWordWrap: "off",
  renderIndicators: true,
});

// A document = one workspace file's Monaco model plus its save bookkeeping. Shared by
// reference between the file's tab and any worktree diff tab, so an edit in one IS the
// edit in the other and saving either saves the buffer.
interface Doc {
  path: string;
  model: monaco.editor.ITextModel;
  savedVersion: number;
  mtime?: number;
}

const docs = new Map<string, Doc>();

// A media file opens as a preview pane, not a Monaco model — Monaco itself is
// text-only. A diff tab holds an `original` model (HEAD or index) against either the
// shared document (worktree diffs) or a read-only `modifiedRO` model (staged diffs,
// deleted files).
type TabKind = "text" | "image" | "video" | "audio" | "diff";

interface Tab {
  key: string; // the map key: the path, or diff:<w|s>:<path>
  path: string;
  kind: TabKind;
  doc?: Doc;
  original?: monaco.editor.ITextModel;
  modifiedRO?: monaco.editor.ITextModel;
  diff?: { repo: string; rel: string; staged: boolean; deleted: boolean };
  viewState?: monaco.editor.ICodeEditorViewState | monaco.editor.IDiffEditorViewState | null;
}

const tabs = new Map<string, Tab>();
let active: Tab | undefined;

const MEDIA_KIND: Record<string, TabKind> = {};
const mk = (k: TabKind, exts: string[]) => exts.forEach((e) => (MEDIA_KIND[e] = k));
mk("image", ["png", "jpg", "jpeg", "gif", "svg", "webp", "ico", "bmp", "avif"]);
mk("video", ["mp4", "webm", "mov", "m4v"]);
mk("audio", ["mp3", "wav", "ogg", "m4a", "flac"]);
const mediaKindOf = (name: string): TabKind | undefined => MEDIA_KIND[name.slice(name.lastIndexOf(".") + 1).toLowerCase()];

const isDirty = (t: Tab): boolean => !!t.doc && t.doc.model.getAlternativeVersionId() !== t.doc.savedVersion;
const diffKey = (path: string, staged: boolean): string => `diff:${staged ? "s" : "w"}:${path}`;
const tabTitle = (t: Tab): string => (t.diff ? `${basename(t.path)} (${t.diff.staged ? "Index" : "Working Tree"})` : basename(t.path));

function renderTabs(): void {
  tabsEl.replaceChildren(
    ...[...tabs.values()].map((t) => {
      const el = document.createElement("div");
      el.className = `tab${t === active ? " active" : ""}${isDirty(t) ? " dirty" : ""}`;
      el.setAttribute("role", "tab");
      el.title = t.diff ? `${t.path} — ${t.diff.staged ? "HEAD ↔ index" : "index ↔ working tree"}` : t.path;
      const name = document.createElement("span");
      name.textContent = basename(t.path);
      el.append(name);
      if (t.diff) {
        const suffix = document.createElement("span");
        suffix.className = "suffix";
        suffix.textContent = t.diff.staged ? "(Index)" : "(Working Tree)";
        el.append(suffix);
      }
      const close = document.createElement("button");
      close.className = "close";
      close.title = "Close";
      close.innerHTML = `<span class="x">&times;</span>`;
      close.onclick = (e) => {
        e.stopPropagation();
        closeTab(t);
      };
      el.onclick = () => activate(t);
      el.append(close);
      return el;
    }),
  );
}

function syncUrl(): void {
  const u = new URL(location.href);
  u.searchParams.delete("token"); // promoted to a cookie by the doorman on first load
  u.searchParams.delete("line");
  if (active && !active.diff) u.searchParams.set("file", active.path);
  else u.searchParams.delete("file");
  history.replaceState(null, "", u);
}

const mediaEl = $("media-view");

function renderMedia(t: Tab): void {
  const src = `api/file?path=${encodeURIComponent(t.path)}`;
  const el = t.kind === "image" ? document.createElement("img") : document.createElement(t.kind as "video" | "audio");
  el.setAttribute("src", src);
  if (el instanceof HTMLMediaElement) el.controls = true;
  el.onerror = () => flash(`preview failed to load ${basename(t.path)}`, true);
  mediaEl.replaceChildren(el);
}

function activate(t: Tab): void {
  if (active && active !== t) {
    if (active.kind === "diff") active.viewState = diffEditor.saveViewState();
    else if (active.doc) active.viewState = editor.saveViewState();
  }
  active = t;
  // A successful open supersedes any standing error (errors don't auto-expire).
  if (statusMsg.classList.contains("error")) {
    statusMsg.textContent = "";
    statusMsg.classList.remove("error");
  }
  mediaEl.hidden = true;
  mediaEl.replaceChildren(); // stop any playing video/audio
  diffHost.hidden = true;
  if (t.kind === "diff" && t.original) {
    const modified = t.doc?.model ?? t.modifiedRO!;
    diffHost.hidden = false;
    diffEditor.setModel({ original: t.original, modified });
    diffEditor.updateOptions({ readOnly: !t.doc });
    if (t.viewState) diffEditor.restoreViewState(t.viewState as monaco.editor.IDiffEditorViewState);
    statusLang.textContent = modified.getLanguageId();
  } else if (t.kind === "text" && t.doc) {
    editor.setModel(t.doc.model);
    if (t.viewState) editor.restoreViewState(t.viewState as monaco.editor.ICodeEditorViewState);
    statusLang.textContent = t.doc.model.getLanguageId();
  } else {
    renderMedia(t);
    mediaEl.hidden = false;
    statusLang.textContent = t.kind;
  }
  emptyEl.classList.add("hidden");
  statusPath.textContent = t.diff ? `${t.path}  ·  ${t.diff.staged ? "HEAD ↔ index" : "index ↔ working tree"}` : t.path;
  renderTabs();
  markActiveTreeNode();
  markActiveScmRow();
  syncUrl();
  if (t.kind === "text") editor.focus();
  else if (t.kind === "diff") diffEditor.getModifiedEditor().focus();
}

// Drop a doc once no tab references it.
function releaseDoc(doc: Doc | undefined): void {
  if (!doc) return;
  if ([...tabs.values()].some((t) => t.doc === doc)) return;
  docs.delete(doc.path);
  doc.model.dispose();
}

function closeTab(t: Tab, force = false): void {
  // A shared buffer keeps its edits in the surviving tab — only the LAST tab holding
  // a dirty doc asks.
  const lastHolder = !!t.doc && ![...tabs.values()].some((o) => o !== t && o.doc === t.doc);
  if (!force && lastHolder && isDirty(t) && !confirm(`${t.path} has unsaved changes. Close anyway?`)) return;
  tabs.delete(t.key);
  t.original?.dispose();
  t.modifiedRO?.dispose();
  releaseDoc(t.doc);
  if (active === t) {
    active = [...tabs.values()].pop();
    if (active) activate(active);
    else {
      editor.setModel(null);
      diffEditor.setModel(null);
      diffHost.hidden = true;
      mediaEl.hidden = true;
      mediaEl.replaceChildren();
      emptyEl.classList.remove("hidden");
      statusPath.textContent = "";
      statusLang.textContent = "";
      renderTabs();
      markActiveTreeNode();
      markActiveScmRow();
      syncUrl();
    }
  } else renderTabs();
}

// Load (or reuse) the document for a workspace file. Throws on read failures and on
// binaries — the caller reports.
async function loadDoc(path: string): Promise<Doc> {
  const have = docs.get(path);
  if (have) return have;
  const read = await apiRead(path);
  const head = new Uint8Array(read.bytes.slice(0, 8192));
  if (head.includes(0)) throw new Error(`${basename(path)} looks binary — not opening`);
  const text = new TextDecoder().decode(read.bytes);
  const model = monaco.editor.createModel(text, undefined, monaco.Uri.file(`/${path}`));
  const doc: Doc = { path, model, savedVersion: model.getAlternativeVersionId(), mtime: read.mtime };
  model.onDidChangeContent(() => renderTabs());
  docs.set(path, doc);
  return doc;
}

async function openFile(path: string, line?: number): Promise<void> {
  let t = tabs.get(path);
  const media = mediaKindOf(path);
  if (!t && media) {
    t = { key: path, path, kind: media };
    tabs.set(path, t);
  }
  if (!t) {
    let doc: Doc;
    try {
      doc = await loadDoc(path);
    } catch (e) {
      flash(`open failed: ${(e as Error).message}`, true);
      return;
    }
    t = { key: path, path, kind: "text", doc, viewState: null };
    tabs.set(path, t);
  }
  activate(t);
  void revealInTree(path);
  if (line && line > 0 && t.doc) {
    editor.revealLineInCenter(line);
    editor.setPosition({ lineNumber: line, column: 1 });
  }
}

async function save(): Promise<void> {
  const t = active;
  const d = t?.doc;
  if (!t || !d || !isDirty(t)) return;
  const version = d.model.getAlternativeVersionId();
  try {
    const out = await apiSave(d.path, d.model.getValue(), d.mtime);
    d.savedVersion = version;
    d.mtime = out.mtime;
    warnedStale.delete(d.path);
    renderTabs();
    flash("Saved");
    void refreshGit(true);
  } catch (e) {
    const err = e as Error & { stale?: boolean };
    if (err.stale) {
      // The file moved underneath the editor (agent/terminal). Overwrite or keep the
      // buffer unsaved — reopening the file loads the sandbox version.
      if (confirm(`${d.path} changed in the sandbox since you opened it.\n\nOK overwrites the sandbox version with yours; Cancel keeps your buffer unsaved (close and reopen the file to load the sandbox version).`)) {
        try {
          const out = await apiSave(d.path, d.model.getValue());
          d.savedVersion = version;
          d.mtime = out.mtime;
          renderTabs();
          flash("Saved (overwrote the sandbox version)");
          void refreshGit(true);
        } catch (e2) {
          flash(`save failed: ${(e2 as Error).message}`, true);
        }
      }
      return;
    }
    flash(`save failed: ${err.message}`, true);
  }
}

editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyS, () => void save());
diffEditor.getModifiedEditor().addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyS, () => void save());
// Swallow the browser's save dialog when focus sits outside the editor too.
window.addEventListener("keydown", (e) => {
  if ((e.metaKey || e.ctrlKey) && e.key === "s") {
    e.preventDefault();
    void save();
  }
});
window.addEventListener("beforeunload", (e) => {
  if ([...tabs.values()].some(isDirty)) e.preventDefault();
});

// Open buffers follow the sandbox: agents, terminals and git rewrite files behind the
// editor's back, and the tab must show what's on disk. Clean buffers reload in place
// (an edit, not setValue — cursor, scroll and undo survive); a dirty buffer keeps the
// user's edits and says so once — the stale-save gate decides at save time.
let syncingDocs = false;
const warnedStale = new Set<string>();
async function syncDocs(): Promise<void> {
  if (syncingDocs || !docs.size) return;
  syncingDocs = true;
  try {
    const paths = [...docs.keys()].slice(0, 200);
    const mtimes = await apiStat(paths);
    await Promise.all(
      paths.map(async (path) => {
        const d = docs.get(path);
        const m = mtimes[path];
        if (!d || !m || !d.mtime || m === d.mtime) return;
        if (d.model.getAlternativeVersionId() !== d.savedVersion) {
          if (!warnedStale.has(path)) {
            warnedStale.add(path);
            flash(`${basename(path)} changed in the sandbox — your unsaved edits are kept`, true);
          }
          return;
        }
        const read = await apiRead(path);
        const text = new TextDecoder().decode(read.bytes);
        if (text !== d.model.getValue()) {
          d.model.applyEdits([{ range: d.model.getFullModelRange(), text }]);
          if (active?.doc === d) flash(`${basename(path)} reloaded from the sandbox`);
        }
        d.savedVersion = d.model.getAlternativeVersionId();
        d.mtime = read.mtime ?? m;
        warnedStale.delete(path);
      }),
    );
    renderTabs();
  } catch {
    /* next tick retries */
  } finally {
    syncingDocs = false;
  }
}

// Tab bookkeeping when tree operations move things underneath the editor. A Monaco
// model's URI is fixed, so a rename rebuilds the document; diff tabs on the old path
// are simply closed (their git identity moved with the file).
function retargetTab(oldPath: string, newPath: string): void {
  for (const dt of [...tabs.values()]) if (dt.diff && dt.path === oldPath) closeTab(dt, true);
  const t = tabs.get(oldPath);
  if (!t) return;
  tabs.delete(oldPath);
  if (!t.doc) {
    // media preview: re-key and re-point the preview at the new path
    t.path = newPath;
    t.key = newPath;
    tabs.set(newPath, t);
    if (active === t) activate(t);
    else renderTabs();
    return;
  }
  const wasDirty = isDirty(t);
  const wasActive = active === t;
  const value = t.doc.model.getValue();
  const state = wasActive ? editor.saveViewState() : t.viewState;
  const oldDoc = t.doc;
  const model = monaco.editor.createModel(value, undefined, monaco.Uri.file(`/${newPath}`));
  const doc: Doc = { path: newPath, model, savedVersion: wasDirty ? -1 : model.getAlternativeVersionId(), mtime: oldDoc.mtime };
  model.onDidChangeContent(() => renderTabs());
  docs.set(newPath, doc);
  const nt: Tab = { key: newPath, path: newPath, kind: "text", doc, viewState: state };
  tabs.set(newPath, nt);
  releaseDoc(oldDoc);
  if (wasActive) activate(nt);
  else renderTabs();
}

function dropTabsUnder(path: string): void {
  for (const t of [...tabs.values()]) {
    if (t.path === path || t.path.startsWith(`${path}/`)) closeTab(t, true);
  }
}

function retargetTabsUnder(oldDir: string, newDir: string): void {
  for (const t of [...tabs.values()]) {
    if (t.path.startsWith(`${oldDir}/`)) retargetTab(t.path, `${newDir}${t.path.slice(oldDir.length)}`);
  }
}

// --- file icons -----------------------------------------------------------------
// One folder shape + one file shape, colored by category — legible without an icon font.

const ICON_FOLDER = `<svg viewBox="0 0 16 16"><path d="M1.5 3.5h4l1.5 2h7.5v7h-13z" fill="currentColor" opacity=".85"/></svg>`;
const ICON_FILE = `<svg viewBox="0 0 16 16"><path d="M3.5 1.5h6l3 3v10h-9z" fill="none" stroke="currentColor" stroke-width="1.3"/><path d="M9.5 1.5v3h3" fill="none" stroke="currentColor" stroke-width="1.3"/></svg>`;

const EXT_CATEGORY: Record<string, string> = {};
const cat = (c: string, exts: string[]) => exts.forEach((e) => (EXT_CATEGORY[e] = c));
cat("code", ["ts", "tsx", "js", "jsx", "mjs", "cjs", "py", "go", "rs", "java", "kt", "rb", "php", "c", "h", "cc", "cpp", "hpp", "cs", "swift", "sh", "bash", "zsh", "sql", "vue", "svelte"]);
cat("web", ["html", "htm", "css", "scss", "less"]);
cat("data", ["json", "yml", "yaml", "toml", "xml", "ini", "env", "lock", "csv"]);
cat("doc", ["md", "mdx", "txt", "rst", "pdf"]);
cat("image", ["png", "jpg", "jpeg", "gif", "svg", "webp", "ico", "bmp"]);

const fileCategory = (name: string): string => EXT_CATEGORY[name.slice(name.lastIndexOf(".") + 1).toLowerCase()] ?? "plain";

// Dirs that are almost never what you're looking for: dimmed and sorted last.
const NOISE_DIRS = new Set(["node_modules", ".git", "dist", "build", "out", ".next", ".venv", "venv", "__pycache__", "target", "vendor", ".cache"]);

// --- git state + tree decorations -------------------------------------------------
// Workspace-relative paths throughout (repo dir + repo-relative path). Folders carry
// the strongest status of anything beneath them (VS Code's propagation), files their
// own letter; ignored entries dim.

interface FileGit {
  repo: string;
  rel: string;
  code: string; // the badge letter: M A U D R C
  rank: number;
  index: string;
  work: string;
  renamedFrom?: string;
}

let repos: RepoStatus[] = [];
const fileGit = new Map<string, FileGit>();
const dirGit = new Map<string, { code: string; rank: number }>();
let ignoredDirs: string[] = []; // workspace paths, no trailing slash
const ignoredFiles = new Set<string>();

const CONFLICT_CODES = new Set(["DD", "AU", "UD", "UA", "DU", "AA", "UU"]);

// The badge letter for a status pair, and how loudly it should color a folder: a
// conflict beats everything; a folder with edits reads "modified" even when a file
// beneath it was deleted (deleted files aren't in the tree to see).
function classify(index: string, work: string): { code: string; rank: number } {
  const xy = `${index}${work}`;
  if (CONFLICT_CODES.has(xy)) return { code: "C", rank: 6 };
  if (xy === "??") return { code: "U", rank: 2 };
  if (index === "A") return work === "D" ? { code: "D", rank: 4 } : { code: "A", rank: 3 };
  if (work === "D" || (index === "D" && work === " ")) return { code: "D", rank: 4 };
  if (work === "M" || index === "M" || work === "T" || index === "T") return { code: "M", rank: 5 };
  if (index === "R" || work === "R" || index === "C" || work === "C") return { code: "R", rank: 3 };
  return { code: "M", rank: 5 };
}

const wsPath = (repo: string, rel: string): string => `${repo}/${rel}`.replace(/\/$/, "");

function rebuildGitMaps(): void {
  fileGit.clear();
  dirGit.clear();
  ignoredFiles.clear();
  const dirs: string[] = [];
  for (const r of repos) {
    for (const f of r.files) {
      const { code, rank } = classify(f.index, f.work);
      const p = wsPath(r.dir, f.path);
      fileGit.set(p, { repo: r.dir, rel: f.path, code, rank, index: f.index, work: f.work, renamedFrom: f.renamedFrom });
      let d = parentOf(p);
      while (d) {
        const cur = dirGit.get(d);
        if (!cur || cur.rank < rank) dirGit.set(d, { code, rank });
        d = parentOf(d);
      }
    }
    for (const ig of r.ignored) {
      if (ig.endsWith("/")) dirs.push(wsPath(r.dir, ig));
      else ignoredFiles.add(wsPath(r.dir, ig));
    }
  }
  ignoredDirs = dirs;
}

const isIgnored = (path: string): boolean => ignoredFiles.has(path) || ignoredDirs.some((d) => path === d || path.startsWith(`${d}/`));

// The repo a workspace path belongs to (longest match), or undefined outside every repo.
function repoOf(path: string): RepoStatus | undefined {
  let best: RepoStatus | undefined;
  for (const r of repos) {
    if ((path === r.dir || path.startsWith(`${r.dir}/`)) && (!best || r.dir.length > best.dir.length)) best = r;
  }
  return best;
}
const relOf = (repo: RepoStatus, path: string): string => (path === repo.dir ? "." : path.slice(repo.dir.length + 1));

function decorateRow(row: HTMLElement, path: string, dir: boolean): void {
  const st = dir ? dirGit.get(path) : fileGit.get(path);
  const badge = row.querySelector<HTMLElement>(".badge");
  if (st) {
    row.dataset.git = st.code;
    if (badge) badge.textContent = dir ? "•" : st.code;
  } else {
    delete row.dataset.git;
    if (badge) badge.textContent = "";
  }
  row.classList.toggle("ignored", !st && isIgnored(path));
}

function decorateTree(): void {
  for (const [p, row] of fileRows) decorateRow(row, p, false);
  for (const [p, n] of dirNodes) if (n.rowEl) decorateRow(n.rowEl, p, true);
}

// --- file tree ------------------------------------------------------------------
// Registry-backed: every directory (path "" = the root) keeps its container +
// expansion state, so refreshes and deep reveals can rebuild without losing shape.

interface DirNode {
  kidsEl: HTMLElement;
  rowEl?: HTMLElement; // root has no row
  twistEl?: HTMLElement;
  expanded: boolean;
  loaded: boolean;
  depth: number;
  sig?: string; // signature of the rendered listing (diff-based refresh)
}

const dirNodes = new Map<string, DirNode>();
const fileRows = new Map<string, HTMLElement>();

function markActiveTreeNode(): void {
  for (const [p, el] of fileRows) el.classList.toggle("active", p === active?.path);
}

function makeRow(path: string, name: string, dir: boolean, depth: number): HTMLElement {
  const wrap = document.createElement("div");
  const row = document.createElement("div");
  row.className = `node${dir ? " dir" : ""}${dir && NOISE_DIRS.has(name) ? " dim" : ""}`;
  row.style.paddingLeft = `${8 + depth * 12}px`;
  row.setAttribute("role", "treeitem");
  row.tabIndex = -1;
  row.dataset.path = path;
  row.dataset.dir = String(dir);
  const twist = document.createElement("span");
  twist.className = "twist";
  twist.textContent = dir ? "▸" : "";
  const icon = document.createElement("span");
  icon.className = `icon ${dir ? "cat-folder" : `cat-${fileCategory(name)}`}`;
  icon.innerHTML = dir ? ICON_FOLDER : ICON_FILE;
  const label = document.createElement("span");
  label.className = "name";
  label.textContent = name;
  const badge = document.createElement("span");
  badge.className = "badge";
  row.append(twist, icon, label, badge);
  wrap.append(row);

  row.oncontextmenu = (e) => {
    e.preventDefault();
    openMenu(e.clientX, e.clientY, dir ? dirMenu(path) : fileMenu(path));
  };
  row.draggable = true;
  row.addEventListener("dragstart", (e) => {
    e.dataTransfer?.setData("application/x-isolation-path", path);
    e.dataTransfer!.effectAllowed = "move";
  });

  if (dir) {
    const kids = document.createElement("div");
    kids.style.display = "none";
    wrap.append(kids);
    dirNodes.set(path, { kidsEl: kids, rowEl: row, twistEl: twist, expanded: false, loaded: false, depth });
    row.onclick = () => void toggleDir(path);
    wireDropTarget(row, path);
  } else {
    fileRows.set(path, row);
    row.onclick = () => void openFile(path);
  }
  decorateRow(row, path, dir);
  return wrap;
}

const sortEntries = (entries: Entry[]): Entry[] =>
  entries.sort((a, b) => {
    if (a.dir !== b.dir) return Number(b.dir) - Number(a.dir);
    const an = a.dir && NOISE_DIRS.has(a.name) ? 1 : 0;
    const bn = b.dir && NOISE_DIRS.has(b.name) ? 1 : 0;
    return an - bn || a.name.localeCompare(b.name);
  });

// Signature of a rendered listing — the diff-based refresh skips the DOM entirely
// when a directory's contents haven't changed.
const sigOf = (entries: Entry[]): string => entries.map((e) => `${e.name}${e.dir ? "/" : ""}`).join("\n");

function renderEntries(path: string, entries: Entry[]): void {
  const node = dirNodes.get(path);
  if (!node) return;
  // Rebuilding this container drops any descendant registry entries.
  for (const p of [...dirNodes.keys()]) if (p !== path && (path === "" || p.startsWith(`${path}/`))) dirNodes.delete(p);
  for (const p of [...fileRows.keys()]) if (path === "" || p.startsWith(`${path}/`)) fileRows.delete(p);
  node.kidsEl.replaceChildren(...entries.map((e) => makeRow(path ? `${path}/${e.name}` : e.name, e.name, e.dir, node.depth + (path === "" ? 0 : 1))));
  if (!entries.length) {
    const note = document.createElement("div");
    note.className = "tree-note";
    note.textContent = "(empty)";
    node.kidsEl.replaceChildren(note);
  }
  node.loaded = true;
  node.sig = sigOf(entries);
  markActiveTreeNode();
}

async function listInto(path: string): Promise<void> {
  const node = dirNodes.get(path);
  if (!node) return;
  try {
    renderEntries(path, sortEntries(await apiList(path)));
  } catch (e) {
    const note = document.createElement("div");
    note.className = "tree-note";
    note.textContent = `listing failed: ${(e as Error).message}`;
    node.kidsEl.replaceChildren(note);
  }
}

// Per-entry reconciliation for an already-rendered directory: rows for vanished
// entries are removed (with their registry subtrees), rows for new entries are
// inserted at their sorted position, and KEPT rows are left untouched — an expanded
// subtree survives a sibling appearing or vanishing with zero refetch and zero
// flicker. Element moves via .after() relocate the whole wrap, state included.
function reconcileEntries(path: string, entries: Entry[]): void {
  const node = dirNodes.get(path);
  if (!node) return;
  if (!node.loaded) return renderEntries(path, entries);
  const keyOf = (name: string, dir: boolean) => `${name}${dir ? "/" : ""}`;
  const existing = new Map<string, HTMLElement>();
  for (const wrap of [...node.kidsEl.children] as HTMLElement[]) {
    const row = wrap.firstElementChild as HTMLElement | null;
    if (!row?.dataset?.path) {
      wrap.remove(); // "(empty)" / error notes — recomputed below
      continue;
    }
    existing.set(keyOf(basename(row.dataset.path), row.dataset.dir === "true"), wrap);
  }
  const desiredKeys = new Set(entries.map((e) => keyOf(e.name, e.dir)));
  for (const [key, wrap] of existing) {
    if (desiredKeys.has(key)) continue;
    const p = (wrap.firstElementChild as HTMLElement).dataset.path!;
    wrap.remove();
    dirNodes.delete(p);
    fileRows.delete(p);
    for (const q of [...dirNodes.keys()]) if (q.startsWith(`${p}/`)) dirNodes.delete(q);
    for (const q of [...fileRows.keys()]) if (q.startsWith(`${p}/`)) fileRows.delete(q);
  }
  let cursor: HTMLElement | undefined;
  for (const e of entries) {
    const key = keyOf(e.name, e.dir);
    let wrap = existing.get(key);
    if (!wrap || !wrap.isConnected) {
      wrap = makeRow(path ? `${path}/${e.name}` : e.name, e.name, e.dir, node.depth + (path === "" ? 0 : 1));
    }
    // Only move DOM when the order is actually wrong — .after() on an already-placed
    // node is what would flicker.
    if (cursor ? wrap.previousElementSibling !== cursor : node.kidsEl.firstElementChild !== wrap) {
      if (cursor) cursor.after(wrap);
      else node.kidsEl.prepend(wrap);
    }
    cursor = wrap;
  }
  if (!entries.length) {
    const note = document.createElement("div");
    note.className = "tree-note";
    note.textContent = "(empty)";
    node.kidsEl.replaceChildren(note);
  }
  node.sig = sigOf(entries);
  markActiveTreeNode();
}

async function toggleDir(path: string, force?: boolean): Promise<void> {
  const node = dirNodes.get(path);
  if (!node) return;
  node.expanded = force ?? !node.expanded;
  if (node.twistEl) node.twistEl.textContent = node.expanded ? "▾" : "▸";
  if (node.expanded && !node.loaded) await listInto(path);
  node.kidsEl.style.display = node.expanded ? "" : "none";
}

// Expand every ancestor so `path` is visible; used by deep links and open-file.
async function revealInTree(path: string): Promise<void> {
  const parts = path.split("/");
  let cur = "";
  for (let i = 0; i < parts.length - 1; i++) {
    cur = cur ? `${cur}/${parts[i]}` : parts[i];
    if (!dirNodes.has(cur)) return; // tree disagrees (fresh op, stale list) — refresh will catch up
    await toggleDir(cur, true);
  }
  markActiveTreeNode();
  fileRows.get(path)?.scrollIntoView({ block: "nearest" });
}

// Diff-based refresh: re-list every expanded directory IN PARALLEL, then touch the DOM
// only where a listing actually changed — an unchanged tree refreshes invisibly (no
// collapse/re-expand flicker). A changed directory re-renders and its previously
// expanded descendants that survive are re-expanded. Ops and window focus funnel here.
let reloading = false;
let rerunWanted = false;
async function reloadTree(): Promise<void> {
  // A refresh requested while one is in flight runs AFTER it, not never — dropping it
  // made a post-op refresh silently miss changes when it raced the focus refresh.
  if (reloading) {
    rerunWanted = true;
    return;
  }
  reloading = true;
  try {
    const targets = [...dirNodes.entries()].filter(([, n]) => n.expanded && n.loaded).map(([p]) => p).sort();
    const fetched = await Promise.all(
      targets.map(async (p) => {
        try {
          return { p, entries: sortEntries(await apiList(p)) };
        } catch {
          return { p, entries: undefined }; // vanished or unreadable — a parent's re-render handles it
        }
      }),
    );
    for (const { p, entries } of fetched) {
      const node = dirNodes.get(p); // reconciliation may have dropped a vanished dir
      if (!node || !entries || (node.loaded && node.sig === sigOf(entries))) continue;
      reconcileEntries(p, entries);
    }
  } finally {
    reloading = false;
    if (rerunWanted) {
      rerunWanted = false;
      void reloadTree();
    }
  }
  void refreshGit();
}

// Root registry entry: the tree element itself is the root's container.
dirNodes.set("", { kidsEl: treeEl, expanded: true, loaded: false, depth: 0 });

$("refresh").onclick = () => void reloadTree();
$("collapse").onclick = () => {
  for (const [p] of dirNodes) {
    if (p) void toggleDir(p, false);
  }
};

// Refresh when the tab regains focus (agents/terminals create files while you're away),
// throttled so tab-flipping doesn't hammer the sandbox.
let lastFocusRefresh = 0;
window.addEventListener("focus", () => {
  if (Date.now() - lastFocusRefresh < 5000) return;
  lastFocusRefresh = Date.now();
  void reloadTree();
  void syncDocs();
});

// Keyboard navigation over the visible rows.
treeEl.addEventListener("keydown", (e) => {
  const rows = [...treeEl.querySelectorAll<HTMLElement>(".node")].filter((r) => r.offsetParent !== null);
  const cur = document.activeElement as HTMLElement;
  const i = rows.indexOf(cur);
  const focusRow = (j: number) => rows[Math.max(0, Math.min(rows.length - 1, j))]?.focus();
  if (e.key === "ArrowDown") { e.preventDefault(); focusRow(i + 1); }
  else if (e.key === "ArrowUp") { e.preventDefault(); focusRow(i - 1); }
  else if (e.key === "ArrowRight" && cur?.dataset.dir === "true") { e.preventDefault(); void toggleDir(cur.dataset.path!, true); }
  else if (e.key === "ArrowLeft" && cur?.dataset.path !== undefined) {
    e.preventDefault();
    if (cur.dataset.dir === "true" && dirNodes.get(cur.dataset.path!)?.expanded) void toggleDir(cur.dataset.path!, false);
    else {
      const parent = parentOf(cur.dataset.path!);
      dirNodes.get(parent)?.rowEl?.focus();
    }
  } else if ((e.key === "Enter" || e.key === " ") && cur?.dataset.path !== undefined) {
    e.preventDefault();
    if (cur.dataset.dir === "true") void toggleDir(cur.dataset.path!);
    else void openFile(cur.dataset.path!);
  }
});

// --- context menu ---------------------------------------------------------------

interface MenuItem {
  label: string;
  danger?: boolean;
  disabled?: boolean;
  checked?: boolean; // radio-style mark (branch pickers)
  indent?: boolean; // align with checked siblings
  onAct: () => void;
}
type MenuEntry = MenuItem | "sep" | { heading: string };

const menuEl = document.createElement("div");
menuEl.id = "ctx-menu";
menuEl.hidden = true;
document.body.append(menuEl);

function closeMenu(): void {
  menuEl.hidden = true;
}
document.addEventListener("click", closeMenu);
document.addEventListener("keydown", (e) => e.key === "Escape" && closeMenu());

function openMenu(x: number, y: number, items: MenuEntry[]): void {
  menuEl.replaceChildren(
    ...items.map((it) => {
      if (it === "sep") {
        const s = document.createElement("div");
        s.className = "sep";
        return s;
      }
      if ("heading" in it) {
        const h = document.createElement("div");
        h.className = "heading";
        h.textContent = it.heading;
        return h;
      }
      const b = document.createElement("button");
      b.textContent = it.label;
      if (it.danger) b.classList.add("danger");
      if (it.checked) b.classList.add("checked");
      if (it.indent) b.classList.add("indent");
      b.disabled = !!it.disabled;
      b.onclick = (e) => {
        e.stopPropagation();
        closeMenu();
        it.onAct();
      };
      return b;
    }),
  );
  menuEl.hidden = false;
  const r = menuEl.getBoundingClientRect();
  menuEl.style.left = `${Math.min(x, innerWidth - r.width - 8)}px`;
  menuEl.style.top = `${Math.max(4, Math.min(y, innerHeight - r.height - 8))}px`;
}

// Anchor a menu under an element (buttons that open menus).
const menuBelow = (el: HTMLElement, items: MenuEntry[]): void => {
  const r = el.getBoundingClientRect();
  openMenu(r.left, r.bottom + 4, items);
};

// clipboard-style copy/paste of tree entries
let clipboard: { path: string; cut: boolean } | undefined;

// The Git section of a row's menu — present for anything inside a repo (VS Code's
// explorer shows "Open Changes" and friends only for repo files); actions that don't
// apply to this row's state stay visible but disabled.
function gitMenuFor(path: string, dir: boolean): MenuEntry[] {
  const repo = repoOf(path);
  if (!repo) return [];
  const rel = relOf(repo, path);
  const isRoot = rel === ".";
  const st = dir ? dirGit.get(path) : fileGit.get(path);
  const f = dir ? undefined : fileGit.get(path);
  const hasWork = !!f && (f.work !== " " || f.index === "?");
  const hasIndex = !!f && f.index !== " " && f.index !== "?";
  // Folders: anything beneath with a worktree change / staged change.
  const under = (pred: (g: FileGit) => boolean) => [...fileGit.values()].some((g) => g.repo === repo.dir && `${repo.dir}/${g.rel}`.startsWith(`${path}/`) && pred(g));
  const dirWork = dir && (isRoot ? repo.files.some((x) => x.work !== " " || x.index === "?") : under((g) => g.work !== " " || g.index === "?"));
  const dirIndex = dir && (isRoot ? repo.files.some((x) => x.index !== " " && x.index !== "?") : under((g) => g.index !== " " && g.index !== "?"));
  const paths = [rel];
  const items: MenuEntry[] = ["sep", { heading: `Git · ${repo.dir}` }];
  if (!dir) {
    items.push(
      { label: "Open Changes", disabled: !hasWork, onAct: () => void openDiff(repo.dir, rel, false) },
      { label: "Open Staged Changes", disabled: !hasIndex, onAct: () => void openDiff(repo.dir, rel, true) },
    );
  }
  items.push(
    { label: dir ? "Stage Changes" : "Stage Changes", disabled: dir ? !dirWork : !hasWork, onAct: () => void gitAction(repo.dir, isRoot ? { op: "stageAll" } : { op: "stage", paths }, "staged") },
    { label: "Unstage Changes", disabled: dir ? !dirIndex : !hasIndex, onAct: () => void gitAction(repo.dir, isRoot ? { op: "unstageAll" } : { op: "unstage", paths: f?.renamedFrom ? [rel, f.renamedFrom] : paths }, "unstaged") },
    {
      label: "Discard Changes…",
      danger: true,
      disabled: dir ? !dirWork : !hasWork,
      onAct: () => void confirmDiscard(repo.dir, isRoot ? undefined : paths, dir ? `everything under ${basename(path)}` : basename(path)),
    },
  );
  void st;
  return items;
}

function fileMenu(path: string): MenuEntry[] {
  return [
    { label: "Open", onAct: () => void openFile(path) },
    "sep",
    { label: "Rename…", onAct: () => startInlineRename(path) },
    { label: "Duplicate", onAct: () => void duplicate(path) },
    { label: "Copy", onAct: () => { clipboard = { path, cut: false }; flash(`copied ${basename(path)}`); } },
    { label: "Cut", onAct: () => { clipboard = { path, cut: true }; flash(`cut ${basename(path)}`); } },
    "sep",
    { label: "Download", onAct: () => void download(path) },
    ...gitMenuFor(path, false),
    "sep",
    { label: "Delete…", danger: true, onAct: () => void remove(path) },
  ];
}

function dirMenu(path: string): MenuEntry[] {
  return [
    { label: "New file…", onAct: () => startInlineCreate(path, false) },
    { label: "New folder…", onAct: () => startInlineCreate(path, true) },
    { label: "Upload files…", onAct: () => pickUpload(path) },
    ...(clipboard ? [{ label: `Paste ${basename(clipboard.path)}`, onAct: () => void paste(path) } as MenuItem] : []),
    "sep",
    { label: "Rename…", onAct: () => startInlineRename(path) },
    { label: "Duplicate", onAct: () => void duplicate(path) },
    { label: "Copy", onAct: () => { clipboard = { path, cut: false }; flash(`copied ${basename(path)}`); } },
    { label: "Cut", onAct: () => { clipboard = { path, cut: true }; flash(`cut ${basename(path)}`); } },
    ...gitMenuFor(path, true),
    "sep",
    { label: "Delete…", danger: true, onAct: () => void remove(path) },
  ];
}

function rootMenu(): MenuEntry[] {
  return [
    { label: "New file…", onAct: () => startInlineCreate("", false) },
    { label: "New folder…", onAct: () => startInlineCreate("", true) },
    { label: "Upload files…", onAct: () => pickUpload("") },
    ...(clipboard ? [{ label: `Paste ${basename(clipboard.path)}`, onAct: () => void paste("") } as MenuItem] : []),
    "sep",
    { label: "Refresh", onAct: () => void reloadTree() },
  ];
}

treeEl.addEventListener("contextmenu", (e) => {
  if ((e.target as HTMLElement).closest(".node")) return; // row menus handle themselves
  e.preventDefault();
  openMenu(e.clientX, e.clientY, rootMenu());
});

// --- file operations ------------------------------------------------------------

// Inline input row for create/rename — Enter commits, Esc/blur cancels.
function inlineInput(container: HTMLElement, depth: number, initial: string, commit: (name: string) => void): void {
  const row = document.createElement("div");
  row.className = "node";
  row.style.paddingLeft = `${8 + depth * 12}px`;
  const input = document.createElement("input");
  input.className = "inline-input";
  input.value = initial;
  row.append(document.createElement("span"), input);
  (row.firstChild as HTMLElement).className = "twist";
  container.prepend(row);
  input.focus();
  const dot = initial.lastIndexOf(".");
  input.setSelectionRange(0, dot > 0 ? dot : initial.length);
  let done = false;
  const finish = (val?: string) => {
    if (done) return;
    done = true;
    row.remove();
    const name = val?.trim();
    if (name && !name.includes("/") && name !== "." && name !== "..") commit(name);
  };
  input.onkeydown = (e) => {
    e.stopPropagation();
    if (e.key === "Enter") finish(input.value);
    else if (e.key === "Escape") finish();
  };
  input.onblur = () => finish();
}

function startInlineCreate(dirPath: string, isDir: boolean): void {
  void toggleDir(dirPath || "", true).then(() => {
    const node = dirNodes.get(dirPath);
    if (!node) return;
    inlineInput(node.kidsEl, node.depth + (dirPath === "" ? 0 : 1), "", (name) => {
      const path = dirPath ? `${dirPath}/${name}` : name;
      void apiOp(isDir ? "mkdir" : "create", path)
        .then(async () => {
          await reloadTree();
          await toggleDir(dirPath || "", true);
          if (!isDir) await openFile(path);
        })
        .catch((e) => flash(`${isDir ? "folder" : "file"} not created: ${(e as Error).message}`, true));
    });
  });
}

function startInlineRename(path: string): void {
  const isDir = dirNodes.has(path);
  const row = isDir ? dirNodes.get(path)?.rowEl : fileRows.get(path);
  const wrap = row?.parentElement;
  if (!row || !wrap) return;
  const depth = parseInt(row.style.paddingLeft) ? (parseInt(row.style.paddingLeft) - 8) / 12 : 0;
  row.style.display = "none";
  inlineInput(wrap, depth, basename(path), (name) => {
    row.style.display = "";
    if (name === basename(path)) return;
    const to = parentOf(path) ? `${parentOf(path)}/${name}` : name;
    void apiOp("rename", path, to)
      .then(async () => {
        if (isDir) retargetTabsUnder(path, to);
        else retargetTab(path, to);
        await reloadTree();
      })
      .catch((e) => flash(`rename failed: ${(e as Error).message}`, true));
  });
  // blur-cancel must unhide the original row
  const input = wrap.querySelector<HTMLInputElement>(".inline-input");
  input?.addEventListener("blur", () => (row.style.display = ""));
}

async function duplicate(path: string): Promise<void> {
  const name = basename(path);
  const dot = name.lastIndexOf(".");
  const stem = dot > 0 ? name.slice(0, dot) : name;
  const ext = dot > 0 ? name.slice(dot) : "";
  const dir = parentOf(path);
  for (let i = 1; i <= 9; i++) {
    const candidate = `${stem} copy${i > 1 ? ` ${i}` : ""}${ext}`;
    const to = dir ? `${dir}/${candidate}` : candidate;
    try {
      await apiOp("copy", path, to);
      await reloadTree();
      return;
    } catch (e) {
      if (!/exists/.test((e as Error).message)) {
        flash(`duplicate failed: ${(e as Error).message}`, true);
        return;
      }
    }
  }
  flash("duplicate failed: too many copies", true);
}

async function paste(dirPath: string): Promise<void> {
  if (!clipboard) return;
  const to = dirPath ? `${dirPath}/${basename(clipboard.path)}` : basename(clipboard.path);
  if (to === clipboard.path) return flash("already here", true);
  try {
    await apiOp(clipboard.cut ? "rename" : "copy", clipboard.path, to);
    if (clipboard.cut) {
      if (dirNodes.has(clipboard.path)) retargetTabsUnder(clipboard.path, to);
      else retargetTab(clipboard.path, to);
      clipboard = undefined;
    }
    await reloadTree();
  } catch (e) {
    flash(`paste failed: ${(e as Error).message}`, true);
  }
}

async function remove(path: string): Promise<void> {
  const isDir = dirNodes.has(path);
  if (!confirm(`Delete ${isDir ? "folder" : "file"} "${path}"${isDir ? " and everything in it" : ""}? This can't be undone.`)) return;
  try {
    await apiOp("delete", path);
    dropTabsUnder(path);
    await reloadTree();
    flash(`deleted ${basename(path)}`);
  } catch (e) {
    flash(`delete failed: ${(e as Error).message}`, true);
  }
}

async function download(path: string): Promise<void> {
  try {
    const { bytes } = await apiRead(path);
    const a = document.createElement("a");
    a.href = URL.createObjectURL(new Blob([bytes]));
    a.download = basename(path);
    a.click();
    URL.revokeObjectURL(a.href);
  } catch (e) {
    flash(`download failed: ${(e as Error).message}`, true);
  }
}

// --- upload (picker + OS-file drop) ----------------------------------------------

// XHR, not fetch: upload progress events. Percent shows live in the status bar.
function apiUpload(path: string, file: File, onProgress: (frac: number) => void): Promise<void> {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open("PUT", `api/file?path=${encodeURIComponent(path)}`);
    xhr.upload.onprogress = (e) => e.lengthComputable && onProgress(e.loaded / e.total);
    xhr.onload = () => {
      if (xhr.status < 300) return resolve();
      let msg = `HTTP ${xhr.status}`;
      try {
        msg = (JSON.parse(xhr.responseText) as { error?: string }).error ?? msg;
      } catch { /* non-JSON error body */ }
      reject(new Error(msg));
    };
    xhr.onerror = () => reject(new Error("network error"));
    xhr.send(file);
  });
}

async function uploadFiles(dirPath: string, files: FileList | File[]): Promise<void> {
  const list = [...files];
  let ok = 0;
  for (let i = 0; i < list.length; i++) {
    const f = list[i];
    if (f.size > MAX_UPLOAD) {
      flash(`${f.name} exceeds 10MB — skipped`, true);
      continue;
    }
    const tag = list.length > 1 ? ` (${i + 1}/${list.length})` : "";
    try {
      await apiUpload(dirPath ? `${dirPath}/${f.name}` : f.name, f, (frac) => {
        statusMsg.classList.remove("error");
        statusMsg.textContent = `uploading ${f.name}${tag}… ${Math.round(frac * 100)}%`;
      });
      ok++;
    } catch (e) {
      flash(`upload of ${f.name} failed: ${(e as Error).message}`, true);
    }
  }
  if (ok) flash(`uploaded ${ok} file${ok > 1 ? "s" : ""}`);
  await reloadTree();
}

function pickUpload(dirPath: string): void {
  const input = document.createElement("input");
  input.type = "file";
  input.multiple = true;
  input.onchange = () => input.files && void uploadFiles(dirPath, input.files);
  input.click();
}

// --- drag and drop ---------------------------------------------------------------
// Internal drag = move; a drop carrying OS files = upload into that directory.

function wireDropTarget(el: HTMLElement, dirPath: string): void {
  el.addEventListener("dragover", (e) => {
    e.preventDefault();
    e.stopPropagation();
    el.classList.add("drop-target");
  });
  el.addEventListener("dragleave", () => el.classList.remove("drop-target"));
  el.addEventListener("drop", (e) => {
    e.preventDefault();
    e.stopPropagation();
    el.classList.remove("drop-target");
    void handleDrop(e, dirPath);
  });
}

async function handleDrop(e: DragEvent, dirPath: string): Promise<void> {
  const internal = e.dataTransfer?.getData("application/x-isolation-path");
  if (internal) {
    if (internal === dirPath || dirPath.startsWith(`${internal}/`)) return flash("can't move a folder into itself", true);
    if (parentOf(internal) === dirPath) return;
    const to = dirPath ? `${dirPath}/${basename(internal)}` : basename(internal);
    try {
      await apiOp("rename", internal, to);
      if (dirNodes.has(internal)) retargetTabsUnder(internal, to);
      else retargetTab(internal, to);
      await reloadTree();
      flash(`moved to ${dirPath || "workspace root"}`);
    } catch (err) {
      flash(`move failed: ${(err as Error).message}`, true);
    }
    return;
  }
  if (e.dataTransfer?.files.length) await uploadFiles(dirPath, e.dataTransfer.files);
}

wireDropTarget(treeEl, ""); // the tree background = the workspace root

// --- diffs ----------------------------------------------------------------------

// Model URIs must be unique across every LIVE model: the staged tab's modified side and
// the worktree tab's original side are both "the index", so the tab kind qualifies the
// URI — otherwise opening both diffs of one file throws ("model already exists").
const gitUri = (rev: string, staged: boolean, path: string): monaco.Uri => monaco.Uri.from({ scheme: "isolation-git", path: `/${staged ? "s" : "w"}/${rev}/${path}` });

// Open (or focus) the diff tab for a repo file. Worktree diffs: index → the live
// buffer (editable, Ctrl+S saves). Staged diffs: HEAD → index, read-only.
async function openDiff(repo: string, rel: string, staged: boolean): Promise<void> {
  const path = wsPath(repo, rel);
  const key = diffKey(path, staged);
  const have = tabs.get(key);
  if (have) {
    activate(have);
    return;
  }
  const st = fileGit.get(path);
  const deleted = staged ? st?.index === "D" : st?.work === "D";
  // Models created before a later step fails must be disposed — a leaked model keeps its
  // URI registered, so every retry of this diff would fail from then on.
  let original: monaco.editor.ITextModel | undefined;
  let modifiedRO: monaco.editor.ITextModel | undefined;
  try {
    const orig = await apiGitShow(repo, rel, staged ? "head" : "index");
    if (orig.binary) return flash(`${basename(path)} is binary — no text diff`, true);
    original = monaco.editor.createModel(orig.content ?? "", undefined, gitUri(staged ? "head" : "index", staged, path));
    const t: Tab = { key, path, kind: "diff", original, diff: { repo, rel, staged, deleted: !!deleted }, viewState: null };
    if (staged || deleted) {
      const mod = staged ? await apiGitShow(repo, rel, "index") : { content: "" };
      if (mod.binary) return flash(`${basename(path)} is binary — no text diff`, true);
      modifiedRO = monaco.editor.createModel(mod.content ?? "", undefined, gitUri(staged ? "index" : "deleted", staged, path));
      t.modifiedRO = modifiedRO;
    } else {
      t.doc = await loadDoc(path);
    }
    tabs.set(key, t);
    activate(t);
  } catch (e) {
    flash(`diff failed: ${(e as Error).message}`, true);
  } finally {
    if (!tabs.has(key)) {
      original?.dispose();
      modifiedRO?.dispose();
    }
  }
}

// The original side goes stale when git moves (stage/unstage/commit/discard) — refresh
// every open diff tab of a file whose status changed.
async function refreshDiffTabs(changed: Set<string>): Promise<void> {
  for (const t of [...tabs.values()]) {
    if (!t.diff || !t.original || !changed.has(t.path)) continue;
    try {
      const orig = await apiGitShow(t.diff.repo, t.diff.rel, t.diff.staged ? "head" : "index");
      const text = orig.content ?? "";
      if (text !== t.original.getValue()) t.original.setValue(text);
      if (t.modifiedRO && t.diff.staged) {
        const mod = await apiGitShow(t.diff.repo, t.diff.rel, "index");
        const mtext = mod.content ?? "";
        if (mtext !== t.modifiedRO.getValue()) t.modifiedRO.setValue(mtext);
      }
    } catch {
      /* the next status tick retries */
    }
  }
}

// --- source control section ---------------------------------------------------------

const scmEl = $("scm");
const scmBody = $("scm-body");
const scmCount = $("scm-count");
const scmHead = $("scm-head");

// Per-repo DOM, built once and updated in place so the commit draft survives refreshes.
interface RepoUi {
  root: HTMLElement;
  name: HTMLElement;
  branchBtn: HTMLButtonElement;
  branchLabel: HTMLElement;
  ab: HTMLElement;
  busy: HTMLElement;
  more: HTMLButtonElement;
  error: HTMLElement;
  msg: HTMLTextAreaElement;
  commitBtn: HTMLButtonElement;
  commitMore: HTMLButtonElement;
  stagedGroup: HTMLElement;
  stagedHead: HTMLElement;
  stagedList: HTMLElement;
  changesGroup: HTMLElement;
  changesHead: HTMLElement;
  changesList: HTMLElement;
  note: HTMLElement;
  sig: string;
  busyLabel?: string;
}
const repoUis = new Map<string, RepoUi>();
let gitSigs = new Map<string, string>(); // workspace path → "XY" — drives diff-tab refresh

const stagedHalf = (f: StatusFile): boolean => f.index !== " " && f.index !== "?";
const workHalf = (f: StatusFile): boolean => f.work !== " " || f.index === "?";
const letterFor = (f: StatusFile, staged: boolean): string => {
  const { code } = classify(f.index, f.work);
  if (code === "C") return "C";
  if (staged) return f.index === "R" || f.index === "C" ? "R" : f.index;
  return f.work === "?" ? "U" : f.work;
};

const ibtn = (label: string, title: string, onAct: () => void, danger = false): HTMLButtonElement => {
  const b = document.createElement("button");
  b.className = `ib${danger ? " danger" : ""}`;
  b.textContent = label;
  b.title = title;
  b.onclick = (e) => {
    e.stopPropagation();
    onAct();
  };
  return b;
};

function buildRepoUi(dir: string): RepoUi {
  const root = document.createElement("div");
  root.className = "repo";
  root.dataset.repo = dir;

  const head = document.createElement("div");
  head.className = "repo-head";
  const name = document.createElement("span");
  name.className = "repo-name";
  name.title = `/workspace/${dir}`;
  const branchBtn = document.createElement("button");
  branchBtn.className = "branch-btn";
  branchBtn.title = "Checkout branch…";
  const branchLabel = document.createElement("span");
  branchBtn.innerHTML = `<svg width="10" height="10" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.6"><circle cx="4" cy="3" r="1.8"/><circle cx="4" cy="13" r="1.8"/><circle cx="12" cy="5" r="1.8"/><path d="M4 5v6M12 7c0 3-8 1-8 4"/></svg>`;
  branchBtn.append(branchLabel);
  const ab = document.createElement("span");
  ab.className = "ab";
  const busy = document.createElement("span");
  busy.className = "repo-busy";
  const spacer = document.createElement("span");
  spacer.className = "spacer";
  const more = ibtn("⋯", "More actions…", () => menuBelow(more, repoMoreMenu(dir)));
  head.append(name, branchBtn, ab, busy, spacer, more);

  const error = document.createElement("div");
  error.className = "repo-error";

  const commitBox = document.createElement("div");
  commitBox.className = "commit-box";
  const msg = document.createElement("textarea");
  msg.rows = 2;
  msg.spellcheck = true;
  const commitRow = document.createElement("div");
  commitRow.className = "commit-row";
  const commitBtn = document.createElement("button");
  commitBtn.className = "commit-btn";
  commitBtn.textContent = "✓ Commit";
  const commitMore = document.createElement("button");
  commitMore.className = "commit-more";
  commitMore.textContent = "▾";
  commitMore.title = "More commit actions…";
  commitRow.append(commitBtn, commitMore);
  commitBox.append(msg, commitRow);

  const group = (title: string) => {
    const g = document.createElement("div");
    g.className = "group";
    const h = document.createElement("div");
    h.className = "group-head";
    h.innerHTML = `<span>${title}</span><span class="n"></span>`;
    const acts = document.createElement("span");
    acts.className = "acts";
    h.append(acts);
    const list = document.createElement("div");
    g.append(h, list);
    return { g, h, list, acts };
  };
  const staged = group("Staged Changes");
  const changes = group("Changes");
  staged.acts.append(ibtn("−", "Unstage All Changes", () => void gitAction(dir, { op: "unstageAll" }, "unstaged all")));
  changes.acts.append(
    ibtn("⟲", "Discard All Changes", () => void confirmDiscard(dir, undefined, "ALL changes"), true),
    ibtn("+", "Stage All Changes", () => void gitAction(dir, { op: "stageAll" }, "staged all")),
  );
  const note = document.createElement("div");
  note.className = "scm-note";

  root.append(head, error, commitBox, staged.g, changes.g, note);

  const ui: RepoUi = {
    root, name, branchBtn, branchLabel, ab, busy, more, error, msg, commitBtn, commitMore,
    stagedGroup: staged.g, stagedHead: staged.h, stagedList: staged.list,
    changesGroup: changes.g, changesHead: changes.h, changesList: changes.list,
    note, sig: "",
  };
  branchBtn.onclick = (e) => {
    e.stopPropagation();
    void openBranchMenu(dir, branchBtn);
  };
  const updateCommitBtn = () => {
    const r = repos.find((x) => x.dir === dir);
    const any = !!r && r.files.length > 0;
    commitBtn.disabled = !!ui.busyLabel || !any;
    commitMore.disabled = !!ui.busyLabel || !any;
  };
  msg.addEventListener("input", updateCommitBtn);
  msg.addEventListener("keydown", (e) => {
    e.stopPropagation();
    if ((e.metaKey || e.ctrlKey) && e.key === "Enter") {
      e.preventDefault();
      void commit(dir, {});
    }
  });
  commitBtn.onclick = () => void commit(dir, {});
  commitMore.onclick = (e) => {
    e.stopPropagation();
    menuBelow(commitMore, [
      { label: "Commit", onAct: () => void commit(dir, {}) },
      { label: "Commit & Push", onAct: () => void commit(dir, { push: true }) },
      { label: "Commit (Amend)", onAct: () => void commit(dir, { amend: true }) },
      "sep",
      { label: "Commit All", onAct: () => void commit(dir, { all: true }) },
      { label: "Commit All & Push", onAct: () => void commit(dir, { all: true, push: true }) },
    ]);
  };
  (ui as RepoUi & { updateCommitBtn: () => void }).updateCommitBtn = updateCommitBtn;
  return ui;
}

function scmRow(r: RepoStatus, f: StatusFile, staged: boolean): HTMLElement {
  const path = wsPath(r.dir, f.path);
  const el = document.createElement("div");
  el.className = "scm-row";
  el.dataset.path = path;
  el.dataset.staged = String(staged);
  el.dataset.git = letterFor(f, staged);
  el.title = f.renamedFrom ? `${f.renamedFrom} → ${f.path}` : f.path;
  const icon = document.createElement("span");
  icon.className = `icon cat-${fileCategory(f.path)}`;
  icon.innerHTML = ICON_FILE;
  const name = document.createElement("span");
  name.className = "fname";
  name.textContent = basename(f.path);
  const dirEl = document.createElement("span");
  dirEl.className = "fdir";
  dirEl.textContent = f.path.includes("/") ? f.path.slice(0, f.path.lastIndexOf("/")) : "";
  const acts = document.createElement("span");
  acts.className = "acts";
  const deletedNow = staged ? f.index === "D" : f.work === "D";
  if (!deletedNow) acts.append(ibtn("↗", "Open File", () => void openFile(path)));
  if (staged) acts.append(ibtn("−", "Unstage Changes", () => void gitAction(r.dir, { op: "unstage", paths: f.renamedFrom ? [f.path, f.renamedFrom] : [f.path] }, "unstaged")));
  else {
    acts.append(
      ibtn("⟲", "Discard Changes", () => void confirmDiscard(r.dir, [f.path], basename(f.path)), true),
      ibtn("+", "Stage Changes", () => void gitAction(r.dir, { op: "stage", paths: [f.path] }, "staged")),
    );
  }
  const st = document.createElement("span");
  st.className = "st";
  st.textContent = el.dataset.git;
  el.append(icon, name, dirEl, acts, st);
  el.onclick = () => void openDiff(r.dir, f.path, staged);
  el.oncontextmenu = (e) => {
    e.preventDefault();
    openMenu(e.clientX, e.clientY, [
      { label: staged ? "Open Staged Changes" : "Open Changes", onAct: () => void openDiff(r.dir, f.path, staged) },
      { label: "Open File", disabled: deletedNow, onAct: () => void openFile(path) },
      "sep",
      ...(staged
        ? [{ label: "Unstage Changes", onAct: () => void gitAction(r.dir, { op: "unstage", paths: f.renamedFrom ? [f.path, f.renamedFrom] : [f.path] }, "unstaged") } as MenuItem]
        : [
            { label: "Stage Changes", onAct: () => void gitAction(r.dir, { op: "stage", paths: [f.path] }, "staged") } as MenuItem,
            { label: "Discard Changes…", danger: true, onAct: () => void confirmDiscard(r.dir, [f.path], basename(f.path)) } as MenuItem,
          ]),
    ]);
  };
  return el;
}

function markActiveScmRow(): void {
  for (const row of scmBody.querySelectorAll<HTMLElement>(".scm-row")) {
    row.classList.toggle("active", !!active?.diff && row.dataset.path === active.path && row.dataset.staged === String(active.diff.staged));
  }
}

function renderRepo(r: RepoStatus): void {
  let ui = repoUis.get(r.dir);
  if (!ui) {
    ui = buildRepoUi(r.dir);
    repoUis.set(r.dir, ui);
  }
  ui.name.textContent = r.dir;
  ui.name.title = r.remote ? `/workspace/${r.dir} — ${r.remote}` : `/workspace/${r.dir}`;
  ui.branchLabel.textContent = r.detached ? "detached" : r.branch || "no branch";
  ui.ab.textContent = [r.ahead ? `↑${r.ahead}` : "", r.behind ? `↓${r.behind}` : ""].filter(Boolean).join(" ");
  ui.ab.title = r.upstream ? `${r.ahead} to push · ${r.behind} to pull` : "no upstream — Push publishes the branch";
  ui.msg.placeholder = `Message (${navigator.platform.includes("Mac") ? "⌘" : "Ctrl+"}Enter to commit on "${r.branch || "HEAD"}")`;
  if (r.error) ui.error.textContent = r.error;
  const staged = r.files.filter(stagedHalf);
  const changed = r.files.filter(workHalf);
  ui.stagedHead.querySelector(".n")!.textContent = staged.length ? String(staged.length) : "";
  ui.changesHead.querySelector(".n")!.textContent = changed.length ? String(changed.length) : "";
  ui.stagedGroup.hidden = !staged.length;
  ui.stagedList.replaceChildren(...staged.map((f) => scmRow(r, f, true)));
  ui.changesList.replaceChildren(...changed.map((f) => scmRow(r, f, false)));
  ui.changesGroup.hidden = !changed.length && !!staged.length;
  ui.note.textContent = r.files.length ? "" : r.error ? "" : "No changes";
  ui.note.hidden = !!r.files.length;
  (ui as RepoUi & { updateCommitBtn: () => void }).updateCommitBtn();
}

function renderScm(): void {
  scmEl.hidden = !repos.length;
  if (!repos.length) return;
  const total = repos.reduce((n, r) => n + r.files.length, 0);
  scmCount.textContent = total ? String(total) : "";
  for (const r of repos) {
    const sig = JSON.stringify([r.branch, r.detached, r.upstream, r.ahead, r.behind, r.files, r.error]);
    const ui = repoUis.get(r.dir);
    if (ui && ui.sig === sig && ui.root.isConnected) continue;
    renderRepo(r);
    repoUis.get(r.dir)!.sig = sig;
  }
  // Order + prune.
  const keep = new Set(repos.map((r) => r.dir));
  for (const [dir, ui] of repoUis) {
    if (!keep.has(dir)) {
      ui.root.remove();
      repoUis.delete(dir);
    }
  }
  const ordered = repos.map((r) => repoUis.get(r.dir)!.root);
  if (ordered.some((el, i) => scmBody.children[i] !== el)) scmBody.replaceChildren(...ordered);
  markActiveScmRow();
}

let gitRefreshing = false;
let gitRerun = false;
async function refreshGit(force = false): Promise<void> {
  if (gitRefreshing) {
    gitRerun = gitRerun || force;
    return;
  }
  gitRefreshing = true;
  try {
    repos = await apiGitStatus();
    rebuildGitMaps();
    // Which files' git state moved since the last tick → refresh their diff tabs.
    const next = new Map<string, string>();
    for (const [p, g] of fileGit) next.set(p, `${g.index}${g.work}`);
    const changed = new Set<string>();
    for (const [p, s] of next) if (gitSigs.get(p) !== s) changed.add(p);
    for (const p of gitSigs.keys()) if (!next.has(p)) changed.add(p);
    gitSigs = next;
    renderScm();
    decorateTree();
    if (changed.size) void refreshDiffTabs(changed);
  } catch (e) {
    // The section keeps its last state; the status bar carries the error once.
    if (force) flash(`git: ${(e as Error).message}`, true);
  } finally {
    gitRefreshing = false;
    if (gitRerun) {
      gitRerun = false;
      void refreshGit(true);
    }
  }
}

// One git operation with the repo's busy state, then a refresh. `label` is the
// past-tense status-bar word. Worktree-changing ops reload clean buffers.
async function gitAction(repo: string, body: Record<string, unknown>, label: string): Promise<void> {
  const ui = repoUis.get(repo);
  const verb = String(body.op);
  if (ui?.busyLabel) return flash(`${repo}: still ${ui.busyLabel}`, true);
  if (ui) {
    ui.busyLabel = `${verb}…`;
    ui.busy.textContent = ui.busyLabel;
    ui.error.textContent = "";
    ui.root.querySelectorAll("button").forEach((b) => (b.disabled = true));
  }
  try {
    const out = await apiGitOp(repo, body);
    flash(`${repo}: ${label}${out && /push|pull|fetch/.test(verb) ? ` — ${out.split("\n").pop()}` : ""}`);
    return;
  } catch (e) {
    const m = (e as Error).message;
    if (ui) ui.error.textContent = m;
    flash(`${repo}: ${verb} failed`, true);
    throw e;
  } finally {
    if (ui) {
      ui.busyLabel = undefined;
      ui.busy.textContent = "";
      ui.root.querySelectorAll("button").forEach((b) => (b.disabled = false));
      ui.sig = ""; // force a re-render on the next status
    }
    if (/discard|checkout|createBranch|pull/.test(verb)) {
      await reloadTree();
      await syncDocs();
    }
    await refreshGit(true);
  }
}

async function confirmDiscard(repo: string, paths: string[] | undefined, what: string): Promise<void> {
  const msg = paths
    ? `Discard changes to ${what}?\n\nModified files go back to the index; untracked files are DELETED. This can't be undone.`
    : `Discard ALL changes in ${repo}?\n\nEvery modified file goes back to the index and every untracked file is DELETED. This can't be undone.`;
  if (!confirm(msg)) return;
  await gitAction(repo, paths ? { op: "discard", paths } : { op: "discardAll" }, `discarded ${what}`).catch(() => undefined);
}

async function commit(repo: string, o: { amend?: boolean; all?: boolean; push?: boolean }): Promise<void> {
  const ui = repoUis.get(repo);
  const r = repos.find((x) => x.dir === repo);
  if (!ui || !r) return;
  const message = ui.msg.value.trim();
  if (!message) {
    ui.msg.focus();
    ui.error.textContent = "A commit message is required.";
    return;
  }
  const staged = r.files.filter(stagedHalf);
  let all = !!o.all;
  if (!staged.length && !all) {
    if (!r.files.length) return;
    // VS Code's smart commit: nothing staged → offer to commit everything.
    if (!confirm("There are no staged changes to commit.\n\nStage all changes and commit them?")) return;
    all = true;
  }
  try {
    if (all) await gitAction(repo, { op: "stageAll" }, "staged all");
    await gitAction(repo, { op: "commit", message, amend: !!o.amend }, o.amend ? "amended" : "committed");
    ui.msg.value = "";
    if (o.push) await gitAction(repo, { op: "push" }, "pushed");
  } catch {
    /* surfaced in the repo's error line */
  }
}

// The web page for a remote, from whatever form git holds it in: scp-like ssh
// (git@host:o/r.git), ssh://, https with credentials, and the Credential Vault's
// gateway rewrite (https://<gateway>/git/<host>/<o>/<r>) all resolve to https://host/o/r.
function browseUrl(remote: string | undefined): string | undefined {
  if (!remote) return undefined;
  let u: URL | undefined;
  const scp = /^(?:[\w.-]+@)?([\w.-]+):(?!\/\/)(.+)$/.exec(remote);
  if (scp) u = new URL(`https://${scp[1]}/${scp[2]}`);
  else {
    try {
      u = new URL(remote);
    } catch {
      return undefined;
    }
    if (u.protocol === "ssh:" || u.protocol === "git:") u = new URL(`https://${u.hostname}${u.pathname}`);
    else if (u.protocol !== "https:" && u.protocol !== "http:") return undefined;
    const gw = /^\/git\/([\w.-]+)\/(.+)$/.exec(u.pathname);
    if (gw) u = new URL(`https://${gw[1]}/${gw[2]}`);
  }
  u.username = "";
  u.password = "";
  u.search = "";
  u.hash = "";
  u.pathname = u.pathname.replace(/\.git\/?$/, "").replace(/\/$/, "");
  return u.pathname.length > 1 ? u.toString() : undefined;
}

function openExternal(url: string): void {
  // An anchor click, not window.open: works from inside the SPA's iframe and never
  // hands the opener to the remote host.
  const a = document.createElement("a");
  a.href = url;
  a.target = "_blank";
  a.rel = "noopener noreferrer";
  a.click();
}

function repoMoreMenu(dir: string): MenuEntry[] {
  const r = repos.find((x) => x.dir === dir);
  const any = !!r?.files.length;
  const link = browseUrl(r?.remote);
  return [
    { label: "Open Repository ↗", disabled: !link, onAct: () => link && openExternal(link) },
    "sep",
    { label: "Pull", onAct: () => void gitAction(dir, { op: "pull" }, "pulled").catch(() => undefined) },
    { label: r?.upstream ? "Push" : "Publish Branch", onAct: () => void gitAction(dir, { op: "push" }, r?.upstream ? "pushed" : "published").catch(() => undefined) },
    { label: "Fetch", onAct: () => void gitAction(dir, { op: "fetch" }, "fetched").catch(() => undefined) },
    "sep",
    { label: "Checkout to…", onAct: () => void openBranchMenu(dir, repoUis.get(dir)!.branchBtn) },
    { label: "Create Branch…", onAct: () => void createBranch(dir) },
    "sep",
    { label: "Stage All Changes", disabled: !any, onAct: () => void gitAction(dir, { op: "stageAll" }, "staged all").catch(() => undefined) },
    { label: "Unstage All Changes", disabled: !any, onAct: () => void gitAction(dir, { op: "unstageAll" }, "unstaged all").catch(() => undefined) },
    { label: "Discard All Changes…", danger: true, disabled: !any, onAct: () => void confirmDiscard(dir, undefined, "ALL changes") },
    "sep",
    { label: "Refresh", onAct: () => void refreshGit(true) },
  ];
}

async function openBranchMenu(dir: string, anchor: HTMLElement): Promise<void> {
  try {
    const b = await apiGitBranches(dir);
    const items: MenuEntry[] = [
      { label: "Create new branch…", indent: true, onAct: () => void createBranch(dir) },
      "sep",
      ...b.local.map((name) => ({ label: name, checked: name === b.current, indent: true, onAct: () => void gitAction(dir, { op: "checkout", branch: name }, `switched to ${name}`).catch(() => undefined) }) as MenuItem),
    ];
    if (b.remote.length) {
      items.push("sep", { heading: "Remote" }, ...b.remote.map((name) => ({ label: name, indent: true, onAct: () => void gitAction(dir, { op: "checkout", branch: name }, `switched to ${name}`).catch(() => undefined) }) as MenuItem));
    }
    menuBelow(anchor, items);
  } catch (e) {
    flash(`branches: ${(e as Error).message}`, true);
  }
}

async function createBranch(dir: string): Promise<void> {
  const name = prompt("New branch name (created from the current HEAD and checked out):")?.trim();
  if (!name) return;
  await gitAction(dir, { op: "createBranch", branch: name }, `created ${name}`).catch(() => undefined);
}

// Section chrome: collapse toggle (+ keyboard), refresh, and a drag handle for the
// section height. Both persist per browser.
const SCM_KEY = "isolation.scm";
try {
  const saved = JSON.parse(localStorage.getItem(SCM_KEY) ?? "{}") as { h?: number; collapsed?: boolean };
  if (saved.h) document.documentElement.style.setProperty("--scm-h", `${saved.h}px`);
  if (saved.collapsed) scmEl.classList.add("collapsed");
} catch { /* no storage */ }
const persistScm = () => {
  try {
    localStorage.setItem(SCM_KEY, JSON.stringify({ h: parseInt(getComputedStyle(document.documentElement).getPropertyValue("--scm-h")) || undefined, collapsed: scmEl.classList.contains("collapsed") }));
  } catch { /* no storage */ }
};
const toggleScm = () => {
  scmEl.classList.toggle("collapsed");
  scmHead.setAttribute("aria-expanded", String(!scmEl.classList.contains("collapsed")));
  persistScm();
};
scmHead.onclick = (e) => {
  if ((e.target as HTMLElement).closest("button")) return;
  toggleScm();
};
scmHead.onkeydown = (e) => {
  if (e.key === "Enter" || e.key === " ") {
    e.preventDefault();
    toggleScm();
  }
};
$("scm-refresh").onclick = (e) => {
  e.stopPropagation();
  void refreshGit(true);
};
const resizeEl = $("scm-resize");
resizeEl.addEventListener("pointerdown", (e) => {
  e.preventDefault();
  resizeEl.setPointerCapture(e.pointerId);
  resizeEl.classList.add("dragging");
  const startY = e.clientY;
  const startH = scmEl.getBoundingClientRect().height;
  const sidebarH = scmEl.parentElement!.getBoundingClientRect().height;
  const move = (ev: PointerEvent) => {
    const h = Math.max(120, Math.min(sidebarH - 120, startH - (ev.clientY - startY)));
    document.documentElement.style.setProperty("--scm-h", `${Math.round(h)}px`);
  };
  const up = () => {
    resizeEl.classList.remove("dragging");
    resizeEl.removeEventListener("pointermove", move);
    resizeEl.removeEventListener("pointerup", up);
    persistScm();
  };
  resizeEl.addEventListener("pointermove", move);
  resizeEl.addEventListener("pointerup", up);
});

// Poll while visible: agents and terminals change the working tree behind our back.
setInterval(() => {
  if (document.hidden) return;
  void refreshGit();
  void syncDocs();
}, 4000);

// --- deep links + navigation ----------------------------------------------------

// `isolation:open` lets the surrounding SPA (or anything embedding the view) steer a
// mounted editor to a file/line without a reload. Payload only — no capability beyond
// what the view token already grants — so no origin gate is needed.
window.addEventListener("message", (e) => {
  const d = e.data as { type?: string; file?: string; line?: number } | null;
  if (d && d.type === "isolation:open" && typeof d.file === "string") {
    void openFile(d.file, typeof d.line === "number" ? d.line : undefined);
  }
});

// A small imperative handle for whatever embeds the view (same-origin scripting or
// tests): steer the mounted editor without the postMessage hop.
Object.assign(window as object, { isolationCodeView: { open: openFile, openDiff, save, editor, diffEditor, refreshGit } });

const boot = new URL(location.href).searchParams;
void listInto("").then(() => {
  const file = boot.get("file");
  const line = Number(boot.get("line") ?? "") || undefined;
  if (file) void openFile(file, line);
  else syncUrl(); // still strip the token from the address bar
  void refreshGit(true);
});
