// The Isolation code view (PLAN V1) — a first-party Monaco editor over the doorman's
// execd-backed file API. Served at /v/<viewId>/ by isolation-server itself: no process
// in the sandbox, no code-server. Direct links carry the location in the QUERY
// (?file=<workspace-relative-path>&line=<n>) so the doorman's routing stays untouched,
// and a mounted view navigates in place on a `isolation:open` postMessage instead of
// reloading.
//
// The sidebar is a full file explorer: create/rename/duplicate/delete via a context
// menu, drag-and-drop move (plus OS-file drop = upload), download, clipboard-style
// copy/paste, keyboard navigation, and refresh-on-focus. Saves are stale-guarded:
// the server refuses a write when the file moved underneath the editor.
// The slim entry (generated by scripts/build-editor.mjs): the full editor + monarch
// syntax highlighting, WITHOUT the worker-backed css/html/json/typescript language
// services — projectless single-file services mark every cross-file import as an
// error and need workers we don't ship.
import * as monaco from "monaco-editor/editor/editor.slim.main.js";
import "./editor.css";

// Monaco's language smarts run in a worker; we bundle the base worker next to main.js.
// __WORKER_V__ is stamped by build-editor.mjs so a server upgrade busts the asset cache.
declare const __WORKER_V__: string;
(self as unknown as { MonacoEnvironment: unknown }).MonacoEnvironment = {
  getWorker: () => new Worker(new URL(`./editor.worker.js?v=${__WORKER_V__}`, location.href)),
};

const $ = <T extends HTMLElement>(id: string): T => document.getElementById(id) as T;
const treeEl = $("tree");
const tabsEl = $("tabs");
const emptyEl = $("empty-state");
const statusPath = $("status-path");
const statusLang = $("status-lang");
const statusMsg = $("status-msg");

const MAX_UPLOAD = 10 * 1024 * 1024; // mirrors the server cap

// --- api ------------------------------------------------------------------------

interface Entry {
  name: string;
  dir: boolean;
}

async function apiList(path: string): Promise<Entry[]> {
  const r = await fetch(`api/list?path=${encodeURIComponent(path)}`);
  if (!r.ok) throw new Error(((await r.json().catch(() => ({}))) as { error?: string }).error ?? `HTTP ${r.status}`);
  return ((await r.json()) as { entries: Entry[] }).entries;
}

async function apiRead(path: string): Promise<{ bytes: ArrayBuffer; mtime?: number }> {
  const r = await fetch(`api/file?path=${encodeURIComponent(path)}`);
  if (!r.ok) throw new Error(((await r.json().catch(() => ({}))) as { error?: string }).error ?? `HTTP ${r.status}`);
  const mtime = Number(r.headers.get("X-Iso-Mtime")) || undefined;
  return { bytes: await r.arrayBuffer(), mtime };
}

// Save with the stale gate; expectMtime undefined = unconditional write.
async function apiSave(path: string, content: string | Blob, expectMtime?: number): Promise<{ mtime?: number }> {
  const r = await fetch(`api/file?path=${encodeURIComponent(path)}`, {
    method: "PUT",
    body: content,
    headers: expectMtime ? { "X-Iso-Expect-Mtime": String(expectMtime) } : {},
  });
  const body = (await r.json().catch(() => ({}))) as { error?: string; stale?: boolean; mtime?: number };
  if (!r.ok) {
    const e = new Error(body.error ?? `HTTP ${r.status}`) as Error & { stale?: boolean };
    e.stale = body.stale;
    throw e;
  }
  return { mtime: body.mtime };
}

async function apiOp(op: string, path: string, to?: string): Promise<void> {
  const r = await fetch("api/op", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ op, path, ...(to ? { to } : {}) }),
  });
  if (!r.ok) throw new Error(((await r.json().catch(() => ({}))) as { error?: string }).error ?? `HTTP ${r.status}`);
}

// --- status ---------------------------------------------------------------------

let msgTimer: number | undefined;
function flash(text: string, isError = false): void {
  statusMsg.textContent = text;
  statusMsg.classList.toggle("error", isError);
  if (msgTimer) clearTimeout(msgTimer);
  if (!isError) msgTimer = window.setTimeout(() => (statusMsg.textContent = ""), 2500);
}

const basename = (p: string): string => p.split("/").pop() ?? p;
const parentOf = (p: string): string => (p.includes("/") ? p.slice(0, p.lastIndexOf("/")) : "");

// --- editor ---------------------------------------------------------------------

monaco.editor.defineTheme("isolation-dark", {
  base: "vs-dark",
  inherit: true,
  rules: [],
  colors: {
    "editor.background": "#0b0d10",
    "editor.lineHighlightBackground": "#12161c",
    "editorLineNumber.foreground": "#3d4652",
    "editorLineNumber.activeForeground": "#9aa4b2",
    "editorGutter.background": "#0b0d10",
    "editorWidget.background": "#101318",
    "editorWidget.border": "#232a33",
    "focusBorder": "#232a33",
    "scrollbarSlider.background": "#232a3366",
    "scrollbarSlider.hoverBackground": "#232a33aa",
  },
});

const editor = monaco.editor.create($("editor"), {
  theme: "isolation-dark",
  automaticLayout: true,
  fontSize: 13,
  minimap: { enabled: false },
  scrollBeyondLastLine: false,
  renderWhitespace: "none",
  smoothScrolling: true,
  padding: { top: 8 },
  stickyScroll: { enabled: false },
});

// A media file opens as a preview pane, not a Monaco model — Monaco itself is
// text-only. `model` and friends exist only for kind "text".
type TabKind = "text" | "image" | "video" | "audio";

interface Tab {
  path: string;
  kind: TabKind;
  model?: monaco.editor.ITextModel;
  savedVersion?: number;
  mtime?: number;
  viewState?: monaco.editor.ICodeEditorViewState | null;
}

const tabs = new Map<string, Tab>();
let active: Tab | undefined;

const MEDIA_KIND: Record<string, TabKind> = {};
const mk = (k: TabKind, exts: string[]) => exts.forEach((e) => (MEDIA_KIND[e] = k));
mk("image", ["png", "jpg", "jpeg", "gif", "svg", "webp", "ico", "bmp", "avif"]);
mk("video", ["mp4", "webm", "mov", "m4v"]);
mk("audio", ["mp3", "wav", "ogg", "m4a", "flac"]);
const mediaKindOf = (name: string): TabKind | undefined => MEDIA_KIND[name.slice(name.lastIndexOf(".") + 1).toLowerCase()];

const isDirty = (t: Tab): boolean => !!t.model && t.model.getAlternativeVersionId() !== t.savedVersion;

function renderTabs(): void {
  tabsEl.replaceChildren(
    ...[...tabs.values()].map((t) => {
      const el = document.createElement("div");
      el.className = `tab${t === active ? " active" : ""}${isDirty(t) ? " dirty" : ""}`;
      el.setAttribute("role", "tab");
      el.title = t.path;
      const name = document.createElement("span");
      name.textContent = basename(t.path);
      const close = document.createElement("button");
      close.className = "close";
      close.title = "Close";
      close.innerHTML = `<span class="x">&times;</span>`;
      close.onclick = (e) => {
        e.stopPropagation();
        closeTab(t);
      };
      el.onclick = () => activate(t);
      el.append(name, close);
      return el;
    }),
  );
}

function syncUrl(): void {
  const u = new URL(location.href);
  u.searchParams.delete("token"); // promoted to a cookie by the doorman on first load
  u.searchParams.delete("line");
  if (active) u.searchParams.set("file", active.path);
  else u.searchParams.delete("file");
  history.replaceState(null, "", u);
}

const mediaEl = $("media-view");

function renderMedia(t: Tab): void {
  const src = `api/file?path=${encodeURIComponent(t.path)}`;
  const el = t.kind === "image" ? document.createElement("img") : document.createElement(t.kind);
  el.setAttribute("src", src);
  if (el instanceof HTMLMediaElement) el.controls = true;
  el.onerror = () => flash(`preview failed to load ${basename(t.path)}`, true);
  mediaEl.replaceChildren(el);
}

function activate(t: Tab): void {
  if (active && active !== t && active.model) active.viewState = editor.saveViewState();
  active = t;
  // A successful open supersedes any standing error (errors don't auto-expire).
  if (statusMsg.classList.contains("error")) {
    statusMsg.textContent = "";
    statusMsg.classList.remove("error");
  }
  if (t.kind === "text" && t.model) {
    mediaEl.hidden = true;
    mediaEl.replaceChildren(); // stop any playing video/audio
    editor.setModel(t.model);
    if (t.viewState) editor.restoreViewState(t.viewState);
    statusLang.textContent = t.model.getLanguageId();
  } else {
    renderMedia(t);
    mediaEl.hidden = false;
    statusLang.textContent = t.kind;
  }
  emptyEl.classList.add("hidden");
  statusPath.textContent = t.path;
  renderTabs();
  markActiveTreeNode();
  syncUrl();
  if (t.kind === "text") editor.focus();
}

function closeTab(t: Tab, force = false): void {
  if (!force && isDirty(t) && !confirm(`${t.path} has unsaved changes. Close anyway?`)) return;
  tabs.delete(t.path);
  t.model?.dispose();
  if (active === t) {
    active = [...tabs.values()].pop();
    if (active) activate(active);
    else {
      editor.setModel(null);
      mediaEl.hidden = true;
      mediaEl.replaceChildren();
      emptyEl.classList.remove("hidden");
      statusPath.textContent = "";
      statusLang.textContent = "";
      renderTabs();
      markActiveTreeNode();
      syncUrl();
    }
  } else renderTabs();
}

async function openFile(path: string, line?: number): Promise<void> {
  let t = tabs.get(path);
  const media = mediaKindOf(path);
  if (!t && media) {
    t = { path, kind: media };
    tabs.set(path, t);
  }
  if (!t) {
    let read: { bytes: ArrayBuffer; mtime?: number };
    try {
      read = await apiRead(path);
    } catch (e) {
      flash(`open failed: ${(e as Error).message}`, true);
      return;
    }
    const head = new Uint8Array(read.bytes.slice(0, 8192));
    if (head.includes(0)) {
      flash(`${basename(path)} looks binary — not opening`, true);
      return;
    }
    const text = new TextDecoder().decode(read.bytes);
    const model = monaco.editor.createModel(text, undefined, monaco.Uri.file(`/${path}`));
    t = { path, kind: "text", model, savedVersion: model.getAlternativeVersionId(), mtime: read.mtime, viewState: null };
    model.onDidChangeContent(() => renderTabs());
    tabs.set(path, t);
  }
  activate(t);
  void revealInTree(path);
  if (line && line > 0 && t.model) {
    editor.revealLineInCenter(line);
    editor.setPosition({ lineNumber: line, column: 1 });
  }
}

async function save(): Promise<void> {
  const t = active;
  if (!t?.model || !isDirty(t)) return;
  const version = t.model.getAlternativeVersionId();
  try {
    const out = await apiSave(t.path, t.model!.getValue(), t.mtime);
    t.savedVersion = version;
    t.mtime = out.mtime;
    renderTabs();
    flash("Saved");
  } catch (e) {
    const err = e as Error & { stale?: boolean };
    if (err.stale) {
      // The file moved underneath the editor (agent/terminal). Overwrite or keep the
      // buffer unsaved — reopening the file loads the sandbox version.
      if (confirm(`${t.path} changed in the sandbox since you opened it.\n\nOK overwrites the sandbox version with yours; Cancel keeps your buffer unsaved (close and reopen the file to load the sandbox version).`)) {
        try {
          const out = await apiSave(t.path, t.model!.getValue());
          t.savedVersion = version;
          t.mtime = out.mtime;
          renderTabs();
          flash("Saved (overwrote the sandbox version)");
        } catch (e2) {
          flash(`save failed: ${(e2 as Error).message}`, true);
        }
      }
      return;
    }
    flash(`save failed: ${err.message}`, true);
  }
}

editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyS, () => void save());
// Swallow the browser's save dialog when focus sits outside the editor too.
window.addEventListener("keydown", (e) => {
  if ((e.metaKey || e.ctrlKey) && e.key === "s") {
    e.preventDefault();
    void save();
  }
});
window.addEventListener("beforeunload", (e) => {
  if ([...tabs.values()].some(isDirty)) e.preventDefault();
});

// Tab bookkeeping when tree operations move things underneath the editor.
function retargetTab(oldPath: string, newPath: string): void {
  const t = tabs.get(oldPath);
  if (!t) return;
  tabs.delete(oldPath);
  if (!t.model) {
    // media preview: re-key and re-point the preview at the new path
    t.path = newPath;
    tabs.set(newPath, t);
    if (active === t) activate(t);
    else renderTabs();
    return;
  }
  const wasDirty = isDirty(t);
  const wasActive = active === t;
  const value = t.model.getValue();
  const state = wasActive ? editor.saveViewState() : t.viewState;
  t.model.dispose();
  const model = monaco.editor.createModel(value, undefined, monaco.Uri.file(`/${newPath}`));
  const nt: Tab = { path: newPath, kind: "text", model, savedVersion: wasDirty ? -1 : model.getAlternativeVersionId(), mtime: t.mtime, viewState: state };
  model.onDidChangeContent(() => renderTabs());
  tabs.set(newPath, nt);
  if (wasActive) activate(nt);
  else renderTabs();
}

function dropTabsUnder(path: string): void {
  for (const t of [...tabs.values()]) {
    if (t.path === path || t.path.startsWith(`${path}/`)) closeTab(t, true);
  }
}

function retargetTabsUnder(oldDir: string, newDir: string): void {
  for (const t of [...tabs.values()]) {
    if (t.path.startsWith(`${oldDir}/`)) retargetTab(t.path, `${newDir}${t.path.slice(oldDir.length)}`);
  }
}

// --- file icons -----------------------------------------------------------------
// One folder shape + one file shape, colored by category — legible without an icon font.

const ICON_FOLDER = `<svg viewBox="0 0 16 16"><path d="M1.5 3.5h4l1.5 2h7.5v7h-13z" fill="currentColor" opacity=".85"/></svg>`;
const ICON_FILE = `<svg viewBox="0 0 16 16"><path d="M3.5 1.5h6l3 3v10h-9z" fill="none" stroke="currentColor" stroke-width="1.3"/><path d="M9.5 1.5v3h3" fill="none" stroke="currentColor" stroke-width="1.3"/></svg>`;

const EXT_CATEGORY: Record<string, string> = {};
const cat = (c: string, exts: string[]) => exts.forEach((e) => (EXT_CATEGORY[e] = c));
cat("code", ["ts", "tsx", "js", "jsx", "mjs", "cjs", "py", "go", "rs", "java", "kt", "rb", "php", "c", "h", "cc", "cpp", "hpp", "cs", "swift", "sh", "bash", "zsh", "sql", "vue", "svelte"]);
cat("web", ["html", "htm", "css", "scss", "less"]);
cat("data", ["json", "yml", "yaml", "toml", "xml", "ini", "env", "lock", "csv"]);
cat("doc", ["md", "mdx", "txt", "rst", "pdf"]);
cat("image", ["png", "jpg", "jpeg", "gif", "svg", "webp", "ico", "bmp"]);

const fileCategory = (name: string): string => EXT_CATEGORY[name.slice(name.lastIndexOf(".") + 1).toLowerCase()] ?? "plain";

// Dirs that are almost never what you're looking for: dimmed and sorted last.
const NOISE_DIRS = new Set(["node_modules", ".git", "dist", "build", "out", ".next", ".venv", "venv", "__pycache__", "target", "vendor", ".cache"]);

// --- file tree ------------------------------------------------------------------
// Registry-backed: every directory (path "" = the root) keeps its container +
// expansion state, so refreshes and deep reveals can rebuild without losing shape.

interface DirNode {
  kidsEl: HTMLElement;
  rowEl?: HTMLElement; // root has no row
  twistEl?: HTMLElement;
  expanded: boolean;
  loaded: boolean;
  depth: number;
  sig?: string; // signature of the rendered listing (diff-based refresh)
}

const dirNodes = new Map<string, DirNode>();
const fileRows = new Map<string, HTMLElement>();

function markActiveTreeNode(): void {
  for (const [p, el] of fileRows) el.classList.toggle("active", p === active?.path);
}

function makeRow(path: string, name: string, dir: boolean, depth: number): HTMLElement {
  const wrap = document.createElement("div");
  const row = document.createElement("div");
  row.className = `node${dir ? " dir" : ""}${dir && NOISE_DIRS.has(name) ? " dim" : ""}`;
  row.style.paddingLeft = `${8 + depth * 12}px`;
  row.setAttribute("role", "treeitem");
  row.tabIndex = -1;
  row.dataset.path = path;
  row.dataset.dir = String(dir);
  const twist = document.createElement("span");
  twist.className = "twist";
  twist.textContent = dir ? "▸" : "";
  const icon = document.createElement("span");
  icon.className = `icon ${dir ? "cat-folder" : `cat-${fileCategory(name)}`}`;
  icon.innerHTML = dir ? ICON_FOLDER : ICON_FILE;
  const label = document.createElement("span");
  label.className = "name";
  label.textContent = name;
  row.append(twist, icon, label);
  wrap.append(row);

  row.oncontextmenu = (e) => {
    e.preventDefault();
    openMenu(e.clientX, e.clientY, dir ? dirMenu(path) : fileMenu(path));
  };
  row.draggable = true;
  row.addEventListener("dragstart", (e) => {
    e.dataTransfer?.setData("application/x-isolation-path", path);
    e.dataTransfer!.effectAllowed = "move";
  });

  if (dir) {
    const kids = document.createElement("div");
    kids.style.display = "none";
    wrap.append(kids);
    dirNodes.set(path, { kidsEl: kids, rowEl: row, twistEl: twist, expanded: false, loaded: false, depth });
    row.onclick = () => void toggleDir(path);
    wireDropTarget(row, path);
  } else {
    fileRows.set(path, row);
    row.onclick = () => void openFile(path);
  }
  return wrap;
}

const sortEntries = (entries: Entry[]): Entry[] =>
  entries.sort((a, b) => {
    if (a.dir !== b.dir) return Number(b.dir) - Number(a.dir);
    const an = a.dir && NOISE_DIRS.has(a.name) ? 1 : 0;
    const bn = b.dir && NOISE_DIRS.has(b.name) ? 1 : 0;
    return an - bn || a.name.localeCompare(b.name);
  });

// Signature of a rendered listing — the diff-based refresh skips the DOM entirely
// when a directory's contents haven't changed.
const sigOf = (entries: Entry[]): string => entries.map((e) => `${e.name}${e.dir ? "/" : ""}`).join("\n");

function renderEntries(path: string, entries: Entry[]): void {
  const node = dirNodes.get(path);
  if (!node) return;
  // Rebuilding this container drops any descendant registry entries.
  for (const p of [...dirNodes.keys()]) if (p !== path && (path === "" || p.startsWith(`${path}/`))) dirNodes.delete(p);
  for (const p of [...fileRows.keys()]) if (path === "" || p.startsWith(`${path}/`)) fileRows.delete(p);
  node.kidsEl.replaceChildren(...entries.map((e) => makeRow(path ? `${path}/${e.name}` : e.name, e.name, e.dir, node.depth + (path === "" ? 0 : 1))));
  if (!entries.length) {
    const note = document.createElement("div");
    note.className = "tree-note";
    note.textContent = "(empty)";
    node.kidsEl.replaceChildren(note);
  }
  node.loaded = true;
  node.sig = sigOf(entries);
  markActiveTreeNode();
}

async function listInto(path: string): Promise<void> {
  const node = dirNodes.get(path);
  if (!node) return;
  try {
    renderEntries(path, sortEntries(await apiList(path)));
  } catch (e) {
    const note = document.createElement("div");
    note.className = "tree-note";
    note.textContent = `listing failed: ${(e as Error).message}`;
    node.kidsEl.replaceChildren(note);
  }
}

async function toggleDir(path: string, force?: boolean): Promise<void> {
  const node = dirNodes.get(path);
  if (!node) return;
  node.expanded = force ?? !node.expanded;
  if (node.twistEl) node.twistEl.textContent = node.expanded ? "▾" : "▸";
  if (node.expanded && !node.loaded) await listInto(path);
  node.kidsEl.style.display = node.expanded ? "" : "none";
}

// Expand every ancestor so `path` is visible; used by deep links and open-file.
async function revealInTree(path: string): Promise<void> {
  const parts = path.split("/");
  let cur = "";
  for (let i = 0; i < parts.length - 1; i++) {
    cur = cur ? `${cur}/${parts[i]}` : parts[i];
    if (!dirNodes.has(cur)) return; // tree disagrees (fresh op, stale list) — refresh will catch up
    await toggleDir(cur, true);
  }
  markActiveTreeNode();
  fileRows.get(path)?.scrollIntoView({ block: "nearest" });
}

// Diff-based refresh: re-list every expanded directory IN PARALLEL, then touch the DOM
// only where a listing actually changed — an unchanged tree refreshes invisibly (no
// collapse/re-expand flicker). A changed directory re-renders and its previously
// expanded descendants that survive are re-expanded. Ops and window focus funnel here.
let reloading = false;
let rerunWanted = false;
async function reloadTree(): Promise<void> {
  // A refresh requested while one is in flight runs AFTER it, not never — dropping it
  // made a post-op refresh silently miss changes when it raced the focus refresh.
  if (reloading) {
    rerunWanted = true;
    return;
  }
  reloading = true;
  try {
    const targets = [...dirNodes.entries()].filter(([, n]) => n.expanded && n.loaded).map(([p]) => p).sort();
    const fetched = await Promise.all(
      targets.map(async (p) => {
        try {
          return { p, entries: sortEntries(await apiList(p)) };
        } catch {
          return { p, entries: undefined }; // vanished or unreadable — a parent's re-render handles it
        }
      }),
    );
    for (const { p, entries } of fetched) {
      const node = dirNodes.get(p); // a parent's re-render may have replaced or dropped this dir
      if (!node || !entries || (node.loaded && node.sig === sigOf(entries))) continue;
      const expandedDesc = [...dirNodes.entries()]
        .filter(([q, n]) => q !== p && n.expanded && (p === "" || q.startsWith(`${p}/`)))
        .map(([q]) => q)
        .sort();
      renderEntries(p, entries);
      for (const q of expandedDesc) {
        if (dirNodes.has(q)) await toggleDir(q, true);
      }
    }
  } finally {
    reloading = false;
    if (rerunWanted) {
      rerunWanted = false;
      void reloadTree();
    }
  }
}

// Root registry entry: the tree element itself is the root's container.
dirNodes.set("", { kidsEl: treeEl, expanded: true, loaded: false, depth: 0 });

$("refresh").onclick = () => void reloadTree();
$("collapse").onclick = () => {
  for (const [p] of dirNodes) {
    if (p) void toggleDir(p, false);
  }
};

// Refresh when the tab regains focus (agents/terminals create files while you're away),
// throttled so tab-flipping doesn't hammer the sandbox.
let lastFocusRefresh = 0;
window.addEventListener("focus", () => {
  if (Date.now() - lastFocusRefresh < 5000) return;
  lastFocusRefresh = Date.now();
  void reloadTree();
});

// Keyboard navigation over the visible rows.
treeEl.addEventListener("keydown", (e) => {
  const rows = [...treeEl.querySelectorAll<HTMLElement>(".node")].filter((r) => r.offsetParent !== null);
  const cur = document.activeElement as HTMLElement;
  const i = rows.indexOf(cur);
  const focusRow = (j: number) => rows[Math.max(0, Math.min(rows.length - 1, j))]?.focus();
  if (e.key === "ArrowDown") { e.preventDefault(); focusRow(i + 1); }
  else if (e.key === "ArrowUp") { e.preventDefault(); focusRow(i - 1); }
  else if (e.key === "ArrowRight" && cur?.dataset.dir === "true") { e.preventDefault(); void toggleDir(cur.dataset.path!, true); }
  else if (e.key === "ArrowLeft" && cur?.dataset.path !== undefined) {
    e.preventDefault();
    if (cur.dataset.dir === "true" && dirNodes.get(cur.dataset.path!)?.expanded) void toggleDir(cur.dataset.path!, false);
    else {
      const parent = parentOf(cur.dataset.path!);
      dirNodes.get(parent)?.rowEl?.focus();
    }
  } else if ((e.key === "Enter" || e.key === " ") && cur?.dataset.path !== undefined) {
    e.preventDefault();
    if (cur.dataset.dir === "true") void toggleDir(cur.dataset.path!);
    else void openFile(cur.dataset.path!);
  }
});

// --- context menu ---------------------------------------------------------------

interface MenuItem {
  label: string;
  danger?: boolean;
  onAct: () => void;
}

const menuEl = document.createElement("div");
menuEl.id = "ctx-menu";
menuEl.hidden = true;
document.body.append(menuEl);

function closeMenu(): void {
  menuEl.hidden = true;
}
document.addEventListener("click", closeMenu);
document.addEventListener("keydown", (e) => e.key === "Escape" && closeMenu());

function openMenu(x: number, y: number, items: (MenuItem | "sep")[]): void {
  menuEl.replaceChildren(
    ...items.map((it) => {
      if (it === "sep") {
        const s = document.createElement("div");
        s.className = "sep";
        return s;
      }
      const b = document.createElement("button");
      b.textContent = it.label;
      if (it.danger) b.className = "danger";
      b.onclick = (e) => {
        e.stopPropagation();
        closeMenu();
        it.onAct();
      };
      return b;
    }),
  );
  menuEl.hidden = false;
  const r = menuEl.getBoundingClientRect();
  menuEl.style.left = `${Math.min(x, innerWidth - r.width - 8)}px`;
  menuEl.style.top = `${Math.min(y, innerHeight - r.height - 8)}px`;
}

// clipboard-style copy/paste of tree entries
let clipboard: { path: string; cut: boolean } | undefined;

function fileMenu(path: string): (MenuItem | "sep")[] {
  return [
    { label: "Open", onAct: () => void openFile(path) },
    "sep",
    { label: "Rename…", onAct: () => startInlineRename(path) },
    { label: "Duplicate", onAct: () => void duplicate(path) },
    { label: "Copy", onAct: () => { clipboard = { path, cut: false }; flash(`copied ${basename(path)}`); } },
    { label: "Cut", onAct: () => { clipboard = { path, cut: true }; flash(`cut ${basename(path)}`); } },
    "sep",
    { label: "Download", onAct: () => void download(path) },
    "sep",
    { label: "Delete…", danger: true, onAct: () => void remove(path) },
  ];
}

function dirMenu(path: string): (MenuItem | "sep")[] {
  return [
    { label: "New file…", onAct: () => startInlineCreate(path, false) },
    { label: "New folder…", onAct: () => startInlineCreate(path, true) },
    { label: "Upload files…", onAct: () => pickUpload(path) },
    ...(clipboard ? [{ label: `Paste ${basename(clipboard.path)}`, onAct: () => void paste(path) } as MenuItem] : []),
    "sep",
    { label: "Rename…", onAct: () => startInlineRename(path) },
    { label: "Duplicate", onAct: () => void duplicate(path) },
    { label: "Copy", onAct: () => { clipboard = { path, cut: false }; flash(`copied ${basename(path)}`); } },
    { label: "Cut", onAct: () => { clipboard = { path, cut: true }; flash(`cut ${basename(path)}`); } },
    "sep",
    { label: "Delete…", danger: true, onAct: () => void remove(path) },
  ];
}

function rootMenu(): (MenuItem | "sep")[] {
  return [
    { label: "New file…", onAct: () => startInlineCreate("", false) },
    { label: "New folder…", onAct: () => startInlineCreate("", true) },
    { label: "Upload files…", onAct: () => pickUpload("") },
    ...(clipboard ? [{ label: `Paste ${basename(clipboard.path)}`, onAct: () => void paste("") } as MenuItem] : []),
    "sep",
    { label: "Refresh", onAct: () => void reloadTree() },
  ];
}

treeEl.addEventListener("contextmenu", (e) => {
  if ((e.target as HTMLElement).closest(".node")) return; // row menus handle themselves
  e.preventDefault();
  openMenu(e.clientX, e.clientY, rootMenu());
});

// --- file operations ------------------------------------------------------------

// Inline input row for create/rename — Enter commits, Esc/blur cancels.
function inlineInput(container: HTMLElement, depth: number, initial: string, commit: (name: string) => void): void {
  const row = document.createElement("div");
  row.className = "node";
  row.style.paddingLeft = `${8 + depth * 12}px`;
  const input = document.createElement("input");
  input.className = "inline-input";
  input.value = initial;
  row.append(document.createElement("span"), input);
  (row.firstChild as HTMLElement).className = "twist";
  container.prepend(row);
  input.focus();
  const dot = initial.lastIndexOf(".");
  input.setSelectionRange(0, dot > 0 ? dot : initial.length);
  let done = false;
  const finish = (val?: string) => {
    if (done) return;
    done = true;
    row.remove();
    const name = val?.trim();
    if (name && !name.includes("/") && name !== "." && name !== "..") commit(name);
  };
  input.onkeydown = (e) => {
    e.stopPropagation();
    if (e.key === "Enter") finish(input.value);
    else if (e.key === "Escape") finish();
  };
  input.onblur = () => finish();
}

function startInlineCreate(dirPath: string, isDir: boolean): void {
  void toggleDir(dirPath || "", true).then(() => {
    const node = dirNodes.get(dirPath);
    if (!node) return;
    inlineInput(node.kidsEl, node.depth + (dirPath === "" ? 0 : 1), "", (name) => {
      const path = dirPath ? `${dirPath}/${name}` : name;
      void apiOp(isDir ? "mkdir" : "create", path)
        .then(async () => {
          await listInto(dirPath);
          await toggleDir(dirPath || "", true);
          if (!isDir) await openFile(path);
        })
        .catch((e) => flash(`${isDir ? "folder" : "file"} not created: ${(e as Error).message}`, true));
    });
  });
}

function startInlineRename(path: string): void {
  const isDir = dirNodes.has(path);
  const row = isDir ? dirNodes.get(path)?.rowEl : fileRows.get(path);
  const wrap = row?.parentElement;
  if (!row || !wrap) return;
  const depth = parseInt(row.style.paddingLeft) ? (parseInt(row.style.paddingLeft) - 8) / 12 : 0;
  row.style.display = "none";
  inlineInput(wrap, depth, basename(path), (name) => {
    row.style.display = "";
    if (name === basename(path)) return;
    const to = parentOf(path) ? `${parentOf(path)}/${name}` : name;
    void apiOp("rename", path, to)
      .then(async () => {
        if (isDir) retargetTabsUnder(path, to);
        else retargetTab(path, to);
        await reloadTree();
      })
      .catch((e) => flash(`rename failed: ${(e as Error).message}`, true));
  });
  // blur-cancel must unhide the original row
  const input = wrap.querySelector<HTMLInputElement>(".inline-input");
  input?.addEventListener("blur", () => (row.style.display = ""));
}

async function duplicate(path: string): Promise<void> {
  const name = basename(path);
  const dot = name.lastIndexOf(".");
  const stem = dot > 0 ? name.slice(0, dot) : name;
  const ext = dot > 0 ? name.slice(dot) : "";
  const dir = parentOf(path);
  for (let i = 1; i <= 9; i++) {
    const candidate = `${stem} copy${i > 1 ? ` ${i}` : ""}${ext}`;
    const to = dir ? `${dir}/${candidate}` : candidate;
    try {
      await apiOp("copy", path, to);
      await reloadTree();
      return;
    } catch (e) {
      if (!/exists/.test((e as Error).message)) {
        flash(`duplicate failed: ${(e as Error).message}`, true);
        return;
      }
    }
  }
  flash("duplicate failed: too many copies", true);
}

async function paste(dirPath: string): Promise<void> {
  if (!clipboard) return;
  const to = dirPath ? `${dirPath}/${basename(clipboard.path)}` : basename(clipboard.path);
  if (to === clipboard.path) return flash("already here", true);
  try {
    await apiOp(clipboard.cut ? "rename" : "copy", clipboard.path, to);
    if (clipboard.cut) {
      if (dirNodes.has(clipboard.path)) retargetTabsUnder(clipboard.path, to);
      else retargetTab(clipboard.path, to);
      clipboard = undefined;
    }
    await reloadTree();
  } catch (e) {
    flash(`paste failed: ${(e as Error).message}`, true);
  }
}

async function remove(path: string): Promise<void> {
  const isDir = dirNodes.has(path);
  if (!confirm(`Delete ${isDir ? "folder" : "file"} "${path}"${isDir ? " and everything in it" : ""}? This can't be undone.`)) return;
  try {
    await apiOp("delete", path);
    dropTabsUnder(path);
    await reloadTree();
    flash(`deleted ${basename(path)}`);
  } catch (e) {
    flash(`delete failed: ${(e as Error).message}`, true);
  }
}

async function download(path: string): Promise<void> {
  try {
    const { bytes } = await apiRead(path);
    const a = document.createElement("a");
    a.href = URL.createObjectURL(new Blob([bytes]));
    a.download = basename(path);
    a.click();
    URL.revokeObjectURL(a.href);
  } catch (e) {
    flash(`download failed: ${(e as Error).message}`, true);
  }
}

// --- upload (picker + OS-file drop) ----------------------------------------------

// XHR, not fetch: upload progress events. Percent shows live in the status bar.
function apiUpload(path: string, file: File, onProgress: (frac: number) => void): Promise<void> {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open("PUT", `api/file?path=${encodeURIComponent(path)}`);
    xhr.upload.onprogress = (e) => e.lengthComputable && onProgress(e.loaded / e.total);
    xhr.onload = () => {
      if (xhr.status < 300) return resolve();
      let msg = `HTTP ${xhr.status}`;
      try {
        msg = (JSON.parse(xhr.responseText) as { error?: string }).error ?? msg;
      } catch { /* non-JSON error body */ }
      reject(new Error(msg));
    };
    xhr.onerror = () => reject(new Error("network error"));
    xhr.send(file);
  });
}

async function uploadFiles(dirPath: string, files: FileList | File[]): Promise<void> {
  const list = [...files];
  let ok = 0;
  for (let i = 0; i < list.length; i++) {
    const f = list[i];
    if (f.size > MAX_UPLOAD) {
      flash(`${f.name} exceeds 10MB — skipped`, true);
      continue;
    }
    const tag = list.length > 1 ? ` (${i + 1}/${list.length})` : "";
    try {
      await apiUpload(dirPath ? `${dirPath}/${f.name}` : f.name, f, (frac) => {
        statusMsg.classList.remove("error");
        statusMsg.textContent = `uploading ${f.name}${tag}… ${Math.round(frac * 100)}%`;
      });
      ok++;
    } catch (e) {
      flash(`upload of ${f.name} failed: ${(e as Error).message}`, true);
    }
  }
  if (ok) flash(`uploaded ${ok} file${ok > 1 ? "s" : ""}`);
  await reloadTree();
}

function pickUpload(dirPath: string): void {
  const input = document.createElement("input");
  input.type = "file";
  input.multiple = true;
  input.onchange = () => input.files && void uploadFiles(dirPath, input.files);
  input.click();
}

// --- drag and drop ---------------------------------------------------------------
// Internal drag = move; a drop carrying OS files = upload into that directory.

function wireDropTarget(el: HTMLElement, dirPath: string): void {
  el.addEventListener("dragover", (e) => {
    e.preventDefault();
    e.stopPropagation();
    el.classList.add("drop-target");
  });
  el.addEventListener("dragleave", () => el.classList.remove("drop-target"));
  el.addEventListener("drop", (e) => {
    e.preventDefault();
    e.stopPropagation();
    el.classList.remove("drop-target");
    void handleDrop(e, dirPath);
  });
}

async function handleDrop(e: DragEvent, dirPath: string): Promise<void> {
  const internal = e.dataTransfer?.getData("application/x-isolation-path");
  if (internal) {
    if (internal === dirPath || dirPath.startsWith(`${internal}/`)) return flash("can't move a folder into itself", true);
    if (parentOf(internal) === dirPath) return;
    const to = dirPath ? `${dirPath}/${basename(internal)}` : basename(internal);
    try {
      await apiOp("rename", internal, to);
      if (dirNodes.has(internal)) retargetTabsUnder(internal, to);
      else retargetTab(internal, to);
      await reloadTree();
      flash(`moved to ${dirPath || "workspace root"}`);
    } catch (err) {
      flash(`move failed: ${(err as Error).message}`, true);
    }
    return;
  }
  if (e.dataTransfer?.files.length) await uploadFiles(dirPath, e.dataTransfer.files);
}

wireDropTarget(treeEl, ""); // the tree background = the workspace root

// --- deep links + navigation ----------------------------------------------------

// `isolation:open` lets the surrounding SPA (or anything embedding the view) steer a
// mounted editor to a file/line without a reload. Payload only — no capability beyond
// what the view token already grants — so no origin gate is needed.
window.addEventListener("message", (e) => {
  const d = e.data as { type?: string; file?: string; line?: number } | null;
  if (d && d.type === "isolation:open" && typeof d.file === "string") {
    void openFile(d.file, typeof d.line === "number" ? d.line : undefined);
  }
});

// A small imperative handle for whatever embeds the view (same-origin scripting or
// tests): steer the mounted editor without the postMessage hop.
Object.assign(window as object, { isolationCodeView: { open: openFile, save, editor } });

const boot = new URL(location.href).searchParams;
void listInto("").then(() => {
  const file = boot.get("file");
  const line = Number(boot.get("line") ?? "") || undefined;
  if (file) void openFile(file, line);
  else syncUrl(); // still strip the token from the address bar
});
